// slp/frontend-angular/src/features/report/pages/admin-reports/admin-reports.component.ts
import { CommonModule } from "@angular/common";
import { Component, OnInit, inject } from "@angular/core";
import { FormsModule } from "@angular/forms";
import { Router } from "@angular/router";

import { NzButtonModule } from "ng-zorro-antd/button";
import { NzCardModule } from "ng-zorro-antd/card";
import { NzEmptyModule } from "ng-zorro-antd/empty";
import { NzIconModule } from "ng-zorro-antd/icon";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzMessageService } from "ng-zorro-antd/message";
import { NzPopconfirmModule } from "ng-zorro-antd/popconfirm";
import { NzSpinModule } from "ng-zorro-antd/spin";
import { NzTagModule } from "ng-zorro-antd/tag";
import { TranslateModule, TranslateService } from "@ngx-translate/core";

import { ReportService } from "../../report.service";
import { ReportDto } from "../../report.model";

@Component({
  selector: "app-admin-reports",
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    NzButtonModule,
    NzCardModule,
    NzEmptyModule,
    NzIconModule,
    NzInputModule,
    NzPopconfirmModule,
    NzSpinModule,
    NzTagModule,
    TranslateModule,
  ],
  templateUrl: "./admin-reports.component.html",
})
export class AdminReportsComponent implements OnInit {
  private readonly reportService = inject(ReportService);
  private readonly message = inject(NzMessageService);
  private readonly translate = inject(TranslateService);
  private readonly router = inject(Router);

  reports: ReportDto[] = [];
  loading = false;
  resolvingIds: number[] = [];
  searchTerm = "";

  ngOnInit(): void {
    this.fetchReports();
  }

  fetchReports(): void {
    this.loading = true;
    this.reportService.getUnresolvedReports(this.searchTerm).subscribe({
      next: (data) => {
        this.reports = data;
      },
      error: () => {
        this.message.error(this.translate.instant("report.loadError"));
      },
      complete: () => {
        this.loading = false;
      },
    });
  }

  handleSearch(): void {
    this.fetchReports();
  }

  resolveReport(id: number): void {
    this.resolvingIds = [...this.resolvingIds, id];
    this.reportService.resolveReport(id).subscribe({
      next: () => {
        this.reports = this.reports.filter((r) => r.id !== id);
        this.message.success(this.translate.instant("report.resolveSuccess"));
      },
      error: () => {
        this.message.error(this.translate.instant("report.resolveError"));
      },
      complete: () => {
        this.resolvingIds = this.resolvingIds.filter((rid) => rid !== id);
      },
    });
  }

  deleteComment(report: ReportDto): void {
    this.reportService.deleteComment(report.targetId).subscribe({
      next: () => {
        this.message.success(
          this.translate.instant("report.deleteCommentSuccess")
        );
        this.resolveReport(report.id);
      },
      error: () => {
        this.message.error(this.translate.instant("report.deleteCommentError"));
      },
    });
  }

  disableQuiz(report: ReportDto): void {
    this.reportService.disableQuiz(report.targetId).subscribe({
      next: () => {
        this.message.success(
          this.translate.instant("report.disableQuizSuccess")
        );
        this.resolveReport(report.id);
      },
      error: () => {
        this.message.error(this.translate.instant("report.disableQuizError"));
      },
    });
  }

  viewTarget(report: ReportDto): void {
    switch (report.targetType) {
      case "quiz":
        this.router.navigate(["/quiz", report.targetId]);
        break;
      case "question":
        this.router.navigate(["/questions", report.targetId]);
        break;
      default:
        this.message.info(this.translate.instant("report.viewCommentHint"));
    }
  }

  formatDate(iso: string): string {
    return new Date(iso).toLocaleString();
  }
}
<div class="p-4">
  <h2 class="text-xl font-semibold mb-4 text-gray-800">{{ "nav.reports" | translate }}</h2>

  <nz-input-group [nzSuffix]="searchSuffix" class="mb-6">
    <input
      nz-input
      [(ngModel)]="searchTerm"
      placeholder="{{ 'report.searchPlaceholder' | translate }}"
      (ngModelChange)="handleSearch()"
      data-testid="admin-reports-search"
      class="rounded-md"
    />
  </nz-input-group>
  <ng-template #searchSuffix>
    <i nz-icon nzType="search" class="text-gray-400"></i>
  </ng-template>

  @if (loading) {
    <div class="flex justify-center items-center py-12">
      <nz-spin nzSimple></nz-spin>
    </div>
  } @else {
    <div class="space-y-4">
      @for (report of reports; track report.id) {
        <nz-card 
          nzSize="small" 
          [nzBodyStyle]="{ padding: '1.25rem' }"
          class="shadow-sm border-gray-200"
          data-testid="report-card"
        >
          <div class="grid grid-cols-[120px_1fr] gap-x-4 gap-y-2 text-sm">
            
            <span class="font-medium text-gray-500">{{ "report.id" | translate }}:</span>
            <span class="text-gray-900 font-mono">{{ report.id }}</span>

            <span class="font-medium text-gray-500">{{ "report.reporter" | translate }}:</span>
            <span class="text-gray-900">{{ report.username }}</span>

            <span class="font-medium text-gray-500">{{ "report.target" | translate }}:</span>
            <span class="text-gray-900">
              <span class="capitalize">{{ report.targetType }}</span> 
              <span class="text-gray-400 ml-1">#{{ report.targetId }}</span>
            </span>

            <span class="font-medium text-gray-500">{{ "report.reason" | translate }}:</span>
            <span class="text-gray-700 whitespace-pre-wrap italic border-l-2 border-gray-100 pl-3">
              {{ report.reason }}
            </span>

            <span class="font-medium text-gray-500">{{ "report.createdAt" | translate }}:</span>
            <span class="text-gray-400">{{ formatDate(report.createdAt) }}</span>
          </div>

          <div class="flex flex-wrap gap-2 mt-5 pt-4 border-t border-gray-50">
            <button
              nz-button
              nzType="primary"
              nzGhost
              [nzLoading]="resolvingIds.includes(report.id)"
              (click)="resolveReport(report.id)"
              class="min-h-[44px] px-4 flex items-center justify-center rounded-md"
              data-testid="resolve-report-btn"
            >
              {{ "report.resolve" | translate }}
            </button>

            @if (report.targetType === "comment") {
              <button
                nz-button
                nzDanger
                nzGhost
                nz-popconfirm
                [nzPopconfirmTitle]="'report.deleteCommentConfirm' | translate"
                (nzOnConfirm)="deleteComment(report)"
                class="min-h-[44px] px-4 flex items-center justify-center rounded-md"
                data-testid="delete-comment-btn"
              >
                {{ "report.deleteComment" | translate }}
              </button>
            }

            @if (report.targetType === "quiz") {
              <button
                nz-button
                nzDanger
                nzGhost
                nz-popconfirm
                [nzPopconfirmTitle]="'report.disableQuizConfirm' | translate"
                (nzOnConfirm)="disableQuiz(report)"
                class="min-h-[44px] px-4 flex items-center justify-center rounded-md"
                data-testid="disable-quiz-btn"
              >
                {{ "report.disableQuiz" | translate }}
              </button>
            }

            <button
              nz-button
              class="min-h-[44px] px-4 flex items-center justify-center rounded-md"
              (click)="viewTarget(report)"
              data-testid="view-target-btn"
            >
              <i nz-icon nzType="eye" class="mr-1"></i>
              {{ "report.view" | translate }}
            </button>
          </div>
        </nz-card>
      }
    </div>

    @if (!loading && reports.length === 0) {
      <nz-empty
        [nzNotFoundContent]="'report.adminEmpty' | translate"
        class="mt-12 opacity-60"
      ></nz-empty>
    }
  }
</div>

// slp/frontend-vue/src/features/report/pages/AdminReports.vue
<template>
  <div data-testid="admin-reports-panel">
    <a-input-search
      v-model:value="searchTerm"
      placeholder="Search by reporter, target type, or reason..."
      style="margin-bottom: 16px"
      @search="handleSearch"
      data-testid="admin-reports-search"
    />

    <div v-if="loading" class="loading-state">
      <a-spin />
    </div>

    <template v-else>
      <a-card
        v-for="report in reports"
        :key="report.id"
        class="mobile-card"
        size="small"
      >
        <div class="field-row">
          <span class="field-label">ID:</span>
          <span class="field-value">{{ report.id }}</span>
        </div>
        <div class="field-row">
          <span class="field-label">Reporter:</span>
          <span class="field-value">{{ report.username }}</span>
        </div>
        <div class="field-row">
          <span class="field-label">Target:</span>
          <span class="field-value">
            {{ report.targetType }} #{{ report.targetId }}
          </span>
        </div>
        <div class="field-row">
          <span class="field-label">Reason:</span>
          <span class="field-value reason-text">{{ report.reason }}</span>
        </div>
        <div class="field-row">
          <span class="field-label">Created:</span>
          <span class="field-value">{{ formatDate(report.createdAt) }}</span>
        </div>

        <div class="actions">
          <a-button
            type="primary"
            ghost
            class="touch-button"
            :loading="resolvingIds.includes(report.id)"
            @click="handleResolve(report.id)"
            data-testid="resolve-report-btn"
          >
            Resolve
          </a-button>

          <a-popconfirm
            v-if="report.targetType === 'comment'"
            title="Delete this comment?"
            ok-text="Yes"
            cancel-text="No"
            @confirm="handleDeleteComment(report)"
          >
            <a-button
              danger
              ghost
              class="touch-button"
              data-testid="delete-comment-btn"
            >
              Delete Comment
            </a-button>
          </a-popconfirm>

          <a-popconfirm
            v-if="report.targetType === 'quiz'"
            title="Disable this quiz?"
            ok-text="Yes"
            cancel-text="No"
            @confirm="handleDisableQuiz(report)"
          >
            <a-button
              danger
              ghost
              class="touch-button"
              data-testid="disable-quiz-btn"
            >
              Disable Quiz
            </a-button>
          </a-popconfirm>

          <a-button
            class="touch-button"
            @click="viewTarget(report)"
            data-testid="view-target-btn"
          >
            View
          </a-button>
        </div>
      </a-card>

      <div v-if="!reports.length" class="empty-state" data-testid="no-reports">
        No unresolved reports.
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { message, Spin } from "ant-design-vue";
import { useRouter } from "vue-router";
import apiClient from "@/lib/api/client";
import dayjs from "dayjs";

interface ReportDto {
  id: number;
  userId: number;
  username: string;
  targetType: "quiz" | "question" | "comment";
  targetId: number;
  reason: string;
  resolved: boolean;
  resolvedAt?: string;
  createdAt: string;
}

const ASpin = Spin;

const reports = ref<ReportDto[]>([]);
const loading = ref(false);
const resolvingIds = ref<number[]>([]);
const searchTerm = ref("");
const router = useRouter();

const fetchReports = async () => {
  loading.value = true;
  try {
    const response = await apiClient.get<ReportDto[]>("/reports", {
      params: { search: searchTerm.value },
    });
    reports.value = response.data;
  } catch (err: any) {
    message.error("Failed to load reports");
    console.error(err);
  } finally {
    loading.value = false;
  }
};

const handleSearch = () => {
  fetchReports();
};

const formatDate = (dateStr: string) => {
  return dayjs(dateStr).format("YYYY-MM-DD HH:mm");
};

const handleResolve = async (reportId: number) => {
  resolvingIds.value.push(reportId);
  try {
    await apiClient.post(`/reports/${reportId}/resolve`);
    message.success("Report resolved");
    reports.value = reports.value.filter((r) => r.id !== reportId);
  } catch (err: any) {
    message.error(err.response?.data?.error || "Failed to resolve report");
  } finally {
    resolvingIds.value = resolvingIds.value.filter((id) => id !== reportId);
  }
};

const handleDeleteComment = async (report: ReportDto) => {
  try {
    await apiClient.delete(`/admin/comments/${report.targetId}`);
    message.success("Comment deleted");
    await handleResolve(report.id);
  } catch (err: any) {
    message.error(err.response?.data?.error || "Failed to delete comment");
  }
};

const handleDisableQuiz = async (report: ReportDto) => {
  try {
    await apiClient.post(`/admin/quizzes/${report.targetId}/disable`);
    message.success("Quiz disabled");
    await handleResolve(report.id);
  } catch (err: any) {
    message.error(err.response?.data?.error || "Failed to disable quiz");
  }
};

const viewTarget = (report: ReportDto) => {
  switch (report.targetType) {
    case "quiz":
      router.push(`/quiz/${report.targetId}`);
      break;
    case "comment":
      message.info("Comments are viewed on their parent pages");
      break;
    case "question":
      router.push(`/question/${report.targetId}`);
      break;
    default:
      message.warning("Unknown target type");
  }
};

onMounted(() => {
  fetchReports();
});
</script>

<style scoped>
.mobile-card {
  margin-bottom: 12px;
}
.mobile-card :deep(.ant-card-body) {
  padding: 16px;
}

.field-row {
  display: flex;
  margin-bottom: 8px;
  font-size: 14px;
}
.field-label {
  width: 80px;
  font-weight: 500;
  color: #666;
  flex-shrink: 0;
}
.field-value {
  flex: 1;
  word-break: break-word;
}

/* Show full reason text on mobile instead of truncating */
.reason-text {
  white-space: pre-wrap;
}

.actions {
  display: flex;
  gap: 8px;
  margin-top: 12px;
  flex-wrap: wrap;
}

.touch-button {
  min-height: 44px;
  min-width: 44px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  padding: 0 16px;
}

.loading-state {
  display: flex;
  justify-content: center;
  padding: 32px 0;
}

.empty-state {
  text-align: center;
  color: #999;
  padding: 32px 0;
  font-size: 14px;
}
</style>
