// slp/frontend-vue/src/views/Login.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
    <a-card class="w-full max-w-md">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-bold text-gray-900">Welcome Back</h1>
        <p class="text-gray-600 mt-2">Sign in to your account</p>
      </div>

      <a-form
        :model="form"
        @submit.prevent="handleLogin"
        layout="vertical"
      >
        <a-form-item label="Username" required>
          <a-input
            v-model:value="form.username"
            placeholder="Enter your username"
            size="large"
          >
            <template #prefix>
              <User :size="16" class="text-gray-400" />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item label="Password" required>
          <a-input-password
            v-model:value="form.password"
            placeholder="Enter your password"
            size="large"
          >
            <template #prefix>
              <Lock :size="16" class="text-gray-400" />
            </template>
          </a-input-password>
        </a-form-item>

        <div class="text-right mb-4">
          <a-button type="link" @click="showForgotPassword = true" class="p-0">
            Forgot password?
          </a-button>
        </div>

        <a-button
          type="primary"
          html-type="submit"
          :loading="authStore.loading"
          block
          size="large"
          class="mb-4"
        >
          Sign In
        </a-button>

        <div class="text-center">
          <span class="text-gray-600">Don't have an account? </span>
          <router-link to="/register" class="text-blue-600 hover:text-blue-700">
            Sign up
          </router-link>
        </div>
      </a-form>

      <a-alert
        v-if="authStore.error"
        :message="authStore.error"
        type="error"
        show-icon
        closable
        @close="authStore.clearError"
        class="mt-4"
      />
    </a-card>

    <!-- Forgot Password Modal -->
    <a-modal
      v-model:open="showForgotPassword"
      title="Reset Password"
      @ok="handleForgotPassword"
      :confirm-loading="resetLoading"
    >
      <p class="mb-4">Enter your email address to receive a password reset link.</p>
      <a-input
        v-model:value="resetEmail"
        placeholder="Email address"
        type="email"
      />
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { Card, Form, Input, Button, Alert, Modal, message } from 'ant-design-vue';
import { User, Lock } from 'lucide-vue-next';
import { useAuthStore } from '../stores/auth';

const AForm = Form;
const AFormItem = Form.Item;
const AInput = Input;
const AInputPassword = Input.Password;
const AButton = Button;
const ACard = Card;
const AAlert = Alert;
const AModal = Modal;

const router = useRouter();
const authStore = useAuthStore();

const form = ref({
  username: '',
  password: '',
});

const showForgotPassword = ref(false);
const resetEmail = ref('');
const resetLoading = ref(false);

const handleLogin = async () => {
  const success = await authStore.login(form.value.username, form.value.password);
  if (success) {
    message.success('Login successful!');
    router.push('/dashboard');
  }
};

const handleForgotPassword = async () => {
  if (!resetEmail.value) {
    message.warning('Please enter your email');
    return;
  }

  resetLoading.value = true;
  const success = await authStore.requestPasswordReset(resetEmail.value);
  resetLoading.value = false;
  
  if (success) {
    message.success('Password reset email sent if account exists');
    showForgotPassword.value = false;
    resetEmail.value = '';
  } else {
    message.error('Failed to send reset email');
  }
};
</script>

// slp/frontend-angular/src/app/features/auth/pages/login/login.component.ts
import { Component, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { Router, RouterModule } from "@angular/router";
import { NzCardModule } from "ng-zorro-antd/card";
import { NzFormModule } from "ng-zorro-antd/form";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzAlertModule } from "ng-zorro-antd/alert";
import { NzModalModule } from "ng-zorro-antd/modal";
import { NzIconModule } from "ng-zorro-antd/icon";
import { NzMessageService } from "ng-zorro-antd/message";
import { AuthService } from "../../../../core/services/auth.service";
import { firstValueFrom } from "rxjs";

@Component({
  selector: "app-login",
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    NzCardModule,
    NzFormModule,
    NzInputModule,
    NzButtonModule,
    NzAlertModule,
    NzModalModule,
    NzIconModule,
  ],
  templateUrl: "./login.component.html",
})
export class LoginComponent {
  public authService = inject(AuthService);
  public router = inject(Router);
  private message = inject(NzMessageService);

  form = {
    username: "",
    password: "",
  };
  usernameError = "";
  passwordError = "";
  showVerificationAlert = false;
  resending = false;
  showForgotPassword = false;
  resetEmail = "";
  resetLoading = false;

  loading$ = this.authService.loading$;
  error$ = this.authService.error$;

  constructor() {}

  clearFieldError(field: "username" | "password"): void {
    if (field === "username") this.usernameError = "";
    else this.passwordError = "";
  }

  async handleLogin(): Promise<void> {
    this.usernameError = "";
    this.passwordError = "";
    this.authService.clearError();

    if (!this.form.username.trim()) {
      this.usernameError = "Username is required";
      return;
    }
    if (!this.form.password) {
      this.passwordError = "Password is required";
      return;
    }

    try {
      const result = await firstValueFrom(
        this.authService.login(this.form.username, this.form.password),
      );
      if (result.success) {
        this.message.success("Login successful!");
        this.router.navigate(["/dashboard"]);
      }
    } catch (error: any) {
      if (error.code === "EMAIL_NOT_VERIFIED") {
        this.showVerificationAlert = true;
      } else if (error.code === "ACCOUNT_BANNED") {
        this.message.error(error.message, { nzDuration: 5000 });
      } else if (
        error.code === "USER_NOT_FOUND" ||
        error.code === "INVALID_PASSWORD"
      ) {
        this.passwordError = "Invalid username or password";
      } else {
        this.message.error(error.message || "Login failed");
      }
    }
  }

  async handleForgotPassword(): Promise<void> {
    if (!this.resetEmail) {
      this.message.warning("Please enter your email");
      return;
    }
    this.resetLoading = true;
    try {
      const success = await firstValueFrom(
        this.authService.requestPasswordReset(this.resetEmail),
      );
      if (success) {
        this.message.success("Password reset email sent if account exists");
        this.showForgotPassword = false;
        this.resetEmail = "";
      } else {
        this.message.error("Failed to send reset email");
      }
    } finally {
      this.resetLoading = false;
    }
  }

  async resendVerification(): Promise<void> {
    this.resending = true;
    try {
      const success = await firstValueFrom(
        this.authService.sendVerificationEmail(),
      );
      if (success) {
        this.message.success("Verification email sent!");
        this.showVerificationAlert = false;
      } else {
        this.message.error("Failed to send verification email");
      }
    } finally {
      this.resending = false;
    }
  }
}

<div
  class="min-h-screen bg-linear-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4"
>
  <nz-card class="w-full max-w-md">
    <div class="text-center mb-8">
      <h1 class="text-2xl font-bold text-gray-900">Welcome Back</h1>
      <p class="text-gray-600 mt-2">Sign in to your account</p>
    </div>

    <form nz-form (ngSubmit)="handleLogin()" layout="vertical">
      <nz-form-item>
        <nz-form-label>Username</nz-form-label>
        <nz-form-control [nzErrorTip]="usernameError">
          <nz-input-group nzPrefixIcon="user">
            <input
              nz-input
              [(ngModel)]="form.username"
              name="username"
              placeholder="Enter your username"
              (input)="clearFieldError('username')"
            />
          </nz-input-group>
        </nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label>Password</nz-form-label>
        <nz-form-control [nzErrorTip]="passwordError">
          <nz-input-group nzPrefixIcon="lock">
            <input
              nz-input
              type="password"
              [(ngModel)]="form.password"
              name="password"
              placeholder="Enter your password"
              (input)="clearFieldError('password')"
            />
          </nz-input-group>
        </nz-form-control>
      </nz-form-item>

      <div class="text-right mb-4">
        <a
          (click)="showForgotPassword = true"
          class="text-blue-600 hover:text-blue-700"
        >
          Forgot password?
        </a>
      </div>

      <button
        nz-button
        nzType="primary"
        [nzLoading]="(loading$ | async)!"
        block
        nzSize="large"
        class="mb-4"
      >
        Sign In
      </button>

      <div class="text-center">
        <span class="text-gray-600">Don't have an account? </span>
        <a routerLink="/register" class="text-blue-600 hover:text-blue-700">
          Sign up
        </a>
      </div>

      <nz-alert
        *ngIf="showVerificationAlert"
        nzType="warning"
        nzShowIcon
        [nzCloseable]="true"
        (nzOnClose)="showVerificationAlert = false"
        class="mb-4"
      >
        <span>Your email is not verified. </span>
        <button
          nz-button
          nzType="link"
          (click)="resendVerification()"
          [nzLoading]="resending"
          class="p-0 h-auto"
        >
          Resend verification email
        </button>
      </nz-alert>

      <nz-alert
        *ngIf="(error$ | async) && !usernameError && !passwordError"
        [nzMessage]="error$ | async"
        nzType="error"
        nzShowIcon
        [nzCloseable]="true"
        (nzOnClose)="authService.clearError()"
        class="mt-4"
      />
    </form>
  </nz-card>

  <nz-modal
    [(nzVisible)]="showForgotPassword"
    nzTitle="Reset Password"
    (nzOnOk)="handleForgotPassword()"
    [nzOkLoading]="resetLoading"
  >
    <p class="mb-4">
      Enter your email address to receive a password reset link.
    </p>
    <input
      nz-input
      [(ngModel)]="resetEmail"
      placeholder="Email address"
      type="email"
    />
  </nz-modal>
</div>
