// slp/frontend-vue/src/views/Login.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
    <a-card class="w-full max-w-md">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-bold text-gray-900">Welcome Back</h1>
        <p class="text-gray-600 mt-2">Sign in to your account</p>
      </div>

      <a-form
        :model="form"
        @submit.prevent="handleLogin"
        layout="vertical"
      >
        <a-form-item label="Username" required>
          <a-input
            v-model:value="form.username"
            placeholder="Enter your username"
            size="large"
          >
            <template #prefix>
              <User :size="16" class="text-gray-400" />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item label="Password" required>
          <a-input-password
            v-model:value="form.password"
            placeholder="Enter your password"
            size="large"
          >
            <template #prefix>
              <Lock :size="16" class="text-gray-400" />
            </template>
          </a-input-password>
        </a-form-item>

        <div class="text-right mb-4">
          <a-button type="link" @click="showForgotPassword = true" class="p-0">
            Forgot password?
          </a-button>
        </div>

        <a-button
          type="primary"
          html-type="submit"
          :loading="authStore.loading"
          block
          size="large"
          class="mb-4"
        >
          Sign In
        </a-button>

        <div class="text-center">
          <span class="text-gray-600">Don't have an account? </span>
          <router-link to="/register" class="text-blue-600 hover:text-blue-700">
            Sign up
          </router-link>
        </div>
      </a-form>

      <a-alert
        v-if="authStore.error"
        :message="authStore.error"
        type="error"
        show-icon
        closable
        @close="authStore.clearError"
        class="mt-4"
      />
    </a-card>

    <!-- Forgot Password Modal -->
    <a-modal
      v-model:open="showForgotPassword"
      title="Reset Password"
      @ok="handleForgotPassword"
      :confirm-loading="resetLoading"
    >
      <p class="mb-4">Enter your email address to receive a password reset link.</p>
      <a-input
        v-model:value="resetEmail"
        placeholder="Email address"
        type="email"
      />
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { Card, Form, Input, Button, Alert, Modal, message } from 'ant-design-vue';
import { User, Lock } from 'lucide-vue-next';
import { useAuthStore } from '../stores/auth';

const AForm = Form;
const AFormItem = Form.Item;
const AInput = Input;
const AInputPassword = Input.Password;
const AButton = Button;
const ACard = Card;
const AAlert = Alert;
const AModal = Modal;

const router = useRouter();
const authStore = useAuthStore();

const form = ref({
  username: '',
  password: '',
});

const showForgotPassword = ref(false);
const resetEmail = ref('');
const resetLoading = ref(false);

const handleLogin = async () => {
  const success = await authStore.login(form.value.username, form.value.password);
  if (success) {
    message.success('Login successful!');
    router.push('/dashboard');
  }
};

const handleForgotPassword = async () => {
  if (!resetEmail.value) {
    message.warning('Please enter your email');
    return;
  }

  resetLoading.value = true;
  const success = await authStore.requestPasswordReset(resetEmail.value);
  resetLoading.value = false;
  
  if (success) {
    message.success('Password reset email sent if account exists');
    showForgotPassword.value = false;
    resetEmail.value = '';
  } else {
    message.error('Failed to send reset email');
  }
};
</script>

// slp/frontend-angular/src/features/auth/login.component.ts
import { Component } from '@angular/core';
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
  FormsModule,
} from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { firstValueFrom } from 'rxjs';

import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzAlertModule } from 'ng-zorro-antd/alert';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzMessageService } from 'ng-zorro-antd/message';

import { AuthService } from './auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    RouterLink,
    NzFormModule,
    NzInputModule,
    NzButtonModule,
    NzCardModule,
    NzAlertModule,
    NzModalModule,
    NzIconModule,
  ],
  templateUrl: './login.component.html',
})
export class LoginComponent {
  form: FormGroup;

  usernameError = '';
  passwordError = '';
  generalError = '';

  showVerificationAlert = false;
  resending = false;

  showForgotPassword = false;
  resetEmail = '';
  resetLoading = false;

  showPassword = false;
  loading = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private message: NzMessageService,
  ) {
    this.form = this.fb.group({
      username: ['', Validators.required],
      password: ['', Validators.required],
    });
  }

  clearFieldError(field: 'username' | 'password'): void {
    if (field === 'username') this.usernameError = '';
    else this.passwordError = '';
    this.generalError = '';
  }

  async handleLogin(): Promise<void> {
    this.usernameError = '';
    this.passwordError = '';
    this.generalError = '';

    const { username, password } = this.form.value;

    if (!username?.trim()) {
      this.usernameError = 'Username is required';
      return;
    }
    if (!password) {
      this.passwordError = 'Password is required';
      return;
    }

    this.loading = true;
    const result = await firstValueFrom(this.authService.login(username, password));
    this.loading = false;

    if (result.success) {
      this.message.success('Login successful!');
      this.router.navigate(['/dashboard']);
    } else {
      switch (result.code) {
        case 'EMAIL_NOT_VERIFIED':
          this.showVerificationAlert = true;
          break;
        case 'ACCOUNT_BANNED':
          this.message.error(result.message || 'Account banned');
          break;
        case 'USER_NOT_FOUND':
        case 'INVALID_PASSWORD':
          this.passwordError = 'Invalid username or password';
          break;
        default:
          this.generalError = result.message || 'Login failed';
      }
    }
  }

  async handleForgotPassword(): Promise<void> {
    if (!this.resetEmail) {
      this.message.warning('Please enter your email');
      return;
    }
    this.resetLoading = true;
    const success = await firstValueFrom(
      this.authService.requestPasswordReset(this.resetEmail),
    );
    this.resetLoading = false;

    if (success) {
      this.message.success('Password reset email sent if account exists');
      this.showForgotPassword = false;
      this.resetEmail = '';
    } else {
      this.message.error('Failed to send reset email');
    }
  }

  async resendVerification(): Promise<void> {
    this.resending = true;
    const success = await firstValueFrom(this.authService.sendVerificationEmail());
    this.resending = false;

    if (success) {
      this.message.success('Verification email sent!');
      this.showVerificationAlert = false;
    } else {
      this.message.error('Failed to send verification email');
    }
  }
}

<div
  data-testid="login-container"
  class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4"
>
  <nz-card data-testid="login-card" class="w-full max-w-md shadow-lg">
    <!-- Header -->
    <div data-testid="login-header" class="text-center mb-8">
      <h1 data-testid="login-title" class="text-2xl font-bold text-gray-900">
        Welcome Back
      </h1>
      <p data-testid="login-subtitle" class="text-gray-500 mt-1">
        Sign in to your account
      </p>
    </div>

    <!-- Login Form -->
    <form
      data-testid="login-form"
      nz-form
      [formGroup]="form"
      (ngSubmit)="handleLogin()"
      nzLayout="vertical"
    >
      <!-- Username -->
      <nz-form-item data-testid="form-item-username">
        <nz-form-label nzRequired>Username</nz-form-label>
        <nz-form-control
          [nzValidateStatus]="usernameError ? 'error' : ''"
          [nzErrorTip]="usernameError"
        >
          <nz-input-group nzSize="large" [nzPrefix]="prefixUser">
            <input
              data-testid="input-username"
              nz-input
              formControlName="username"
              placeholder="Enter your username"
              (input)="clearFieldError('username')"
            />
          </nz-input-group>
          <ng-template #prefixUser>
            <i
              nz-icon
              nzType="user"
              nzTheme="outline"
              class="text-gray-400"
            ></i>
          </ng-template>
        </nz-form-control>
      </nz-form-item>

      <!-- Password -->
      <nz-form-item data-testid="form-item-password">
        <nz-form-label nzRequired>Password</nz-form-label>
        <nz-form-control
          [nzValidateStatus]="passwordError ? 'error' : ''"
          [nzErrorTip]="passwordError"
        >
          <nz-input-group
            nzSize="large"
            [nzPrefix]="prefixLock"
            [nzSuffix]="suffixEye"
          >
            <input
              data-testid="input-password"
              nz-input
              [type]="showPassword ? 'text' : 'password'"
              formControlName="password"
              placeholder="Enter your password"
              (input)="clearFieldError('password')"
            />
          </nz-input-group>
          <ng-template #prefixLock>
            <i
              nz-icon
              nzType="lock"
              nzTheme="outline"
              class="text-gray-400"
            ></i>
          </ng-template>
          <ng-template #suffixEye>
            <i
              nz-icon
              [nzType]="showPassword ? 'eye' : 'eye-invisible'"
              nzTheme="outline"
              class="text-gray-400 cursor-pointer"
              (click)="showPassword = !showPassword"
            ></i>
          </ng-template>
        </nz-form-control>
      </nz-form-item>

      <!-- Forgot password link -->
      <div class="text-right -mt-2 mb-4">
        <button
          data-testid="forgot-password-link"
          nz-button
          nzType="link"
          type="button"
          class="!p-0"
          (click)="showForgotPassword = true"
        >
          Forgot password?
        </button>
      </div>

      <!-- Submit -->
      <button
        data-testid="button-submit"
        nz-button
        nzType="primary"
        nzBlock
        nzSize="large"
        [nzLoading]="loading"
        type="submit"
        class="mb-4"
      >
        Sign In
      </button>

      <!-- Register link -->
      <div
        data-testid="register-redirect-container"
        class="text-center text-sm"
      >
        <span data-testid="register-redirect-text" class="text-gray-500"
          >Don't have an account?
        </span>
        <a
          data-testid="link-register"
          routerLink="/register"
          class="text-blue-600 hover:text-blue-700 font-medium"
          >Sign up</a
        >
      </div>
    </form>

    <!-- Email not verified alert -->
    <nz-alert
      *ngIf="showVerificationAlert"
      data-testid="verification-alert"
      nzType="warning"
      nzShowIcon
      nzCloseable
      (nzOnClose)="showVerificationAlert = false"
      [nzMessage]="verifyAlertMsg"
      class="mt-4"
    ></nz-alert>
    <ng-template #verifyAlertMsg>
      <span>Your email is not verified. </span>
      <button
        nz-button
        nzType="link"
        class="!p-0"
        (click)="resendVerification()"
        [nzLoading]="resending"
      >
        Resend verification email
      </button>
    </ng-template>

    <!-- General error alert -->
    <nz-alert
      *ngIf="generalError"
      data-testid="error-alert"
      [nzMessage]="generalError"
      nzType="error"
      nzShowIcon
      nzCloseable
      (nzOnClose)="generalError = ''"
      class="mt-4"
    ></nz-alert>
  </nz-card>
</div>

<!-- Forgot Password Modal -->
<nz-modal
  data-testid="forgot-password-modal"
  [(nzVisible)]="showForgotPassword"
  nzTitle="Reset Password"
  (nzOnOk)="handleForgotPassword()"
  [nzOkLoading]="resetLoading"
  nzOkText="Send Reset Link"
>
  <ng-container *nzModalContent>
    <p class="mb-4 text-gray-600">
      Enter your email address to receive a password reset link.
    </p>
    <input
      data-testid="reset-email-input"
      nz-input
      [(ngModel)]="resetEmail"
      placeholder="Email address"
      type="email"
    />
  </ng-container>
</nz-modal>
