// slp/frontend-vue/src/views/Register.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
    <a-card class="w-full max-w-md">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-bold text-gray-900">Create Account</h1>
        <p class="text-gray-600 mt-2">Sign up to get started</p>
      </div>

      <a-form
        :model="form"
        @submit.prevent="handleRegister"
        layout="vertical"
      >
        <a-form-item label="Username" required>
          <a-input
            v-model:value="form.username"
            placeholder="Choose a username"
            size="large"
          >
            <template #prefix>
              <User :size="16" class="text-gray-400" />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item label="Email" required>
          <a-input
            v-model:value="form.email"
            placeholder="Enter your email"
            type="email"
            size="large"
          >
            <template #prefix>
              <Mail :size="16" class="text-gray-400" />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item label="Password" required>
          <a-input-password
            v-model:value="form.password"
            placeholder="Create a password"
            size="large"
          >
            <template #prefix>
              <Lock :size="16" class="text-gray-400" />
            </template>
          </a-input-password>
        </a-form-item>

        <a-form-item label="Confirm Password" required>
          <a-input-password
            v-model:value="form.confirmPassword"
            placeholder="Confirm your password"
            size="large"
          >
            <template #prefix>
              <Lock :size="16" class="text-gray-400" />
            </template>
          </a-input-password>
        </a-form-item>

        <a-button
          type="primary"
          html-type="submit"
          :loading="authStore.loading"
          block
          size="large"
          class="mb-4"
        >
          Sign Up
        </a-button>

        <div class="text-center">
          <span class="text-gray-600">Already have an account? </span>
          <router-link to="/login" class="text-blue-600 hover:text-blue-700">
            Sign in
          </router-link>
        </div>
      </a-form>

      <a-alert
        v-if="authStore.error"
        :message="authStore.error"
        type="error"
        show-icon
        closable
        @close="authStore.clearError"
        class="mt-4"
      />
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { Card, Form, Input, Button, Alert, message } from 'ant-design-vue';
import { User, Mail, Lock } from 'lucide-vue-next';
import { useAuthStore } from '../stores/auth';

const AForm = Form;
const AFormItem = Form.Item;
const AInput = Input;
const AInputPassword = Input.Password;
const AButton = Button;
const ACard = Card;
const AAlert = Alert;

const router = useRouter();
const authStore = useAuthStore();

const form = ref({
  username: '',
  email: '',
  password: '',
  confirmPassword: '',
});

const handleRegister = async () => {
  if (form.value.password !== form.value.confirmPassword) {
    message.error('Passwords do not match');
    return;
  }

  const success = await authStore.register(
    form.value.username,
    form.value.email,
    form.value.password
  );
  
  if (success) {
    message.success('Registration successful! Please login.');
    router.push('/login');
  }
};
</script>

// slp/frontend-angular/src/features/auth/register.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators, ReactiveFormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { CommonModule } from '@angular/common';
import { firstValueFrom } from 'rxjs';

import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzAlertModule } from 'ng-zorro-antd/alert';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzMessageService } from 'ng-zorro-antd/message';

import { AuthService } from './auth.service';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    RouterLink,
    NzFormModule,
    NzInputModule,
    NzButtonModule,
    NzCardModule,
    NzAlertModule,
    NzIconModule,
  ],
  templateUrl: './register.component.html',
})
export class RegisterComponent {
  form: FormGroup;
  loading = false;
  error = '';
  showPassword = false;
  showConfirmPassword = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private message: NzMessageService,
  ) {
    this.form = this.fb.group(
      {
        username: ['', [Validators.required, Validators.minLength(3)]],
        email: ['', [Validators.required, Validators.email]],
        password: ['', [Validators.required, Validators.minLength(6)]],
        confirmPassword: ['', Validators.required],
      },
      { validators: this.passwordMatchValidator },
    );
  }

  private passwordMatchValidator(group: FormGroup): { mismatch: boolean } | null {
    return group.get('password')?.value === group.get('confirmPassword')?.value
      ? null
      : { mismatch: true };
  }

  get passwordMismatch(): boolean {
    return (
      !!this.form.errors?.['mismatch'] &&
      !!this.form.get('confirmPassword')?.dirty
    );
  }

  async handleRegister(): Promise<void> {
    if (this.form.invalid) {
      Object.values(this.form.controls).forEach(c => c.markAsDirty());
      if (this.passwordMismatch) {
        this.error = 'Passwords do not match';
      }
      return;
    }

    this.error = '';
    this.loading = true;

    const { username, email, password } = this.form.value;
    const success = await firstValueFrom(this.authService.register(username, email, password));
    this.loading = false;

    if (success) {
      this.message.success('Registration successful! Please check your email to verify your account.');
      this.router.navigate(['/login']);
    } else {
      this.error = 'Registration failed. Please try again.';
    }
  }
}

<div
  data-testid="registration-container"
  class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4"
>
  <nz-card data-testid="registration-card" class="w-full max-w-md shadow-lg">

    <!-- Header -->
    <div data-testid="registration-header" class="text-center mb-8">
      <h1 data-testid="registration-title" class="text-2xl font-bold text-gray-900">
        Create Account
      </h1>
      <p data-testid="registration-subtitle" class="text-gray-500 mt-1">
        Sign up to get started
      </p>
    </div>

    <!-- Register Form -->
    <form
      data-testid="registration-form"
      nz-form
      [formGroup]="form"
      (ngSubmit)="handleRegister()"
      nzLayout="vertical"
    >
      <!-- Username -->
      <nz-form-item data-testid="form-item-username">
        <nz-form-label nzRequired>Username</nz-form-label>
        <nz-form-control
          [nzValidateStatus]="form.get('username')?.invalid && form.get('username')?.dirty ? 'error' : ''"
          nzErrorTip="Username must be at least 3 characters"
        >
          <nz-input-group nzSize="large" [nzPrefix]="prefixUser">
            <input
              data-testid="input-username"
              nz-input
              formControlName="username"
              placeholder="Choose a username"
            />
          </nz-input-group>
          <ng-template #prefixUser>
            <i nz-icon nzType="user" nzTheme="outline" class="text-gray-400"></i>
          </ng-template>
        </nz-form-control>
      </nz-form-item>

      <!-- Email -->
      <nz-form-item data-testid="form-item-email">
        <nz-form-label nzRequired>Email</nz-form-label>
        <nz-form-control
          [nzValidateStatus]="form.get('email')?.invalid && form.get('email')?.dirty ? 'error' : ''"
          nzErrorTip="Please enter a valid email address"
        >
          <nz-input-group nzSize="large" [nzPrefix]="prefixMail">
            <input
              data-testid="input-email"
              nz-input
              formControlName="email"
              placeholder="Enter your email"
              type="email"
            />
          </nz-input-group>
          <ng-template #prefixMail>
            <i nz-icon nzType="mail" nzTheme="outline" class="text-gray-400"></i>
          </ng-template>
        </nz-form-control>
      </nz-form-item>

      <!-- Password -->
      <nz-form-item data-testid="form-item-password">
        <nz-form-label nzRequired>Password</nz-form-label>
        <nz-form-control
          [nzValidateStatus]="form.get('password')?.invalid && form.get('password')?.dirty ? 'error' : ''"
          nzErrorTip="Password must be at least 6 characters"
        >
          <nz-input-group nzSize="large" [nzPrefix]="prefixLock" [nzSuffix]="suffixEye1">
            <input
              data-testid="input-password"
              nz-input
              [type]="showPassword ? 'text' : 'password'"
              formControlName="password"
              placeholder="Create a password"
            />
          </nz-input-group>
          <ng-template #prefixLock>
            <i nz-icon nzType="lock" nzTheme="outline" class="text-gray-400"></i>
          </ng-template>
          <ng-template #suffixEye1>
            <i
              nz-icon
              [nzType]="showPassword ? 'eye' : 'eye-invisible'"
              nzTheme="outline"
              class="text-gray-400 cursor-pointer"
              (click)="showPassword = !showPassword"
            ></i>
          </ng-template>
        </nz-form-control>
      </nz-form-item>

      <!-- Confirm Password -->
      <nz-form-item data-testid="form-item-confirm-password">
        <nz-form-label nzRequired>Confirm Password</nz-form-label>
        <nz-form-control
          [nzValidateStatus]="passwordMismatch ? 'error' : ''"
          nzErrorTip="Passwords do not match"
        >
          <nz-input-group nzSize="large" [nzPrefix]="prefixLock2" [nzSuffix]="suffixEye2">
            <input
              data-testid="input-confirm-password"
              nz-input
              [type]="showConfirmPassword ? 'text' : 'password'"
              formControlName="confirmPassword"
              placeholder="Confirm your password"
            />
          </nz-input-group>
          <ng-template #prefixLock2>
            <i nz-icon nzType="lock" nzTheme="outline" class="text-gray-400"></i>
          </ng-template>
          <ng-template #suffixEye2>
            <i
              nz-icon
              [nzType]="showConfirmPassword ? 'eye' : 'eye-invisible'"
              nzTheme="outline"
              class="text-gray-400 cursor-pointer"
              (click)="showConfirmPassword = !showConfirmPassword"
            ></i>
          </ng-template>
        </nz-form-control>
      </nz-form-item>

      <!-- Submit -->
      <button
        data-testid="button-submit"
        nz-button
        nzType="primary"
        nzBlock
        nzSize="large"
        [nzLoading]="loading"
        type="submit"
        class="mb-4"
      >
        Sign Up
      </button>

      <!-- Login link -->
      <div data-testid="login-redirect-container" class="text-center text-sm">
        <span data-testid="login-redirect-text" class="text-gray-500">Already have an account? </span>
        <a data-testid="link-login" routerLink="/login" class="text-blue-600 hover:text-blue-700 font-medium">
          Sign in
        </a>
      </div>
    </form>

    <!-- Error alert -->
    <nz-alert
      *ngIf="error"
      data-testid="error-alert"
      [nzMessage]="error"
      nzType="error"
      nzShowIcon
      nzCloseable
      (nzOnClose)="error = ''"
      class="mt-4"
    ></nz-alert>

  </nz-card>
</div>
