// slp/frontend-angular/src/features/question/components/question-form.component.ts
// src/features/question/components/question-form.component.ts
import {
  Component,
  Input,
  Output,
  EventEmitter,
  OnInit,
  OnChanges,
  SimpleChanges,
  inject,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  FormBuilder,
  FormGroup,
  Validators,
  ReactiveFormsModule,
} from "@angular/forms";
import { NzFormModule } from "ng-zorro-antd/form";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzSelectModule } from "ng-zorro-antd/select";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzMessageService } from "ng-zorro-antd/message";
import { TagSelectorComponent } from "../../../components/tag-selector/tag-selector.component";
import { MultipleChoiceComponent } from "./multiple-choice.component";
import { TrueFalseComponent } from "./true-false.component";
import { FillBlankComponent } from "./fill-blank.component";
import { OrderingComponent } from "./ordering.component";
import { MatchingComponent } from "./matching.component";
import { QuestionDto, CreateQuestionPayload } from "../question.model";

@Component({
  selector: "app-question-form",
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NzFormModule,
    NzInputModule,
    NzSelectModule,
    NzButtonModule,
    TagSelectorComponent,
    MultipleChoiceComponent,
    TrueFalseComponent,
    FillBlankComponent,
    OrderingComponent,
    MatchingComponent,
  ],
  template: `
    <form nz-form [formGroup]="form" (ngSubmit)="onSubmit()" (keydown.enter)="$event.preventDefault()">
      <!-- Title -->
      <nz-form-item>
        <nz-form-label [nzRequired]="true">Title</nz-form-label>
        <nz-form-control>
          <input
            nz-input
            formControlName="content"
            placeholder="Enter question title"
          />
        </nz-form-control>
      </nz-form-item>

      <!-- Description -->
      <nz-form-item>
        <nz-form-label>Description (optional)</nz-form-label>
        <nz-form-control>
          <textarea
            nz-input
            formControlName="description"
            rows="3"
            placeholder="Additional description"
          ></textarea>
        </nz-form-control>
      </nz-form-item>

      <!-- Type -->
      <nz-form-item>
        <nz-form-label [nzRequired]="true">Type</nz-form-label>
        <nz-form-control>
          <nz-select
            formControlName="type"
            (ngModelChange)="onTypeChange($event)"
          >
            <nz-option
              nzValue="multiple_choice"
              nzLabel="Multiple Choice"
            ></nz-option>
            <nz-option nzValue="true_false" nzLabel="True/False"></nz-option>
            <nz-option
              nzValue="fill_blank"
              nzLabel="Fill in the Blank"
            ></nz-option>
            <nz-option nzValue="ordering" nzLabel="Ordering"></nz-option>
            <nz-option nzValue="matching" nzLabel="Matching"></nz-option>
          </nz-select>
        </nz-form-control>
      </nz-form-item>

      <!-- Type‑specific components -->
      <div [ngSwitch]="form.get('type')?.value">
        <app-multiple-choice
          *ngSwitchCase="'multiple_choice'"
          [options]="multipleChoiceOptions"
          [correctAnswers]="multipleChoiceCorrect"
          (optionsChange)="setMultipleChoiceOptions($event)"
          (correctAnswersChange)="setMultipleChoiceCorrect($event)"
        >
        </app-multiple-choice>

        <app-true-false
          *ngSwitchCase="'true_false'"
          [answer]="trueFalseAnswer"
          (answerChange)="trueFalseAnswer = $event"
        >
        </app-true-false>

        <app-fill-blank
          *ngSwitchCase="'fill_blank'"
          [answer]="fillBlankAnswer"
          [questionTitle]="form.get('content')?.value"
          (answerChange)="fillBlankAnswer = $event"
        >
        </app-fill-blank>

        <app-ordering
          *ngSwitchCase="'ordering'"
          [items]="orderingItems"
          (itemsChange)="orderingItems = $event"
        >
        </app-ordering>

        <app-matching
          *ngSwitchCase="'matching'"
          [pairs]="matchingPairs"
          (pairsChange)="matchingPairs = $event"
        >
        </app-matching>
      </div>

      <!-- Explanation -->
      <nz-form-item>
        <nz-form-label>Explanation (optional)</nz-form-label>
        <nz-form-control>
          <textarea
            nz-input
            formControlName="explanation"
            rows="3"
            placeholder="Explain the correct answer"
          ></textarea>
        </nz-form-control>
      </nz-form-item>

      <!-- Tags -->
      <nz-form-item>
        <nz-form-label>Tags</nz-form-label>
        <nz-form-control>
          <app-tag-selector [formControl]="tagsControl"> </app-tag-selector>
        </nz-form-control>
      </nz-form-item>

      <!-- Actions -->
      <div class="flex justify-end gap-2 mt-4">
        <button nz-button (click)="onCancel()">Cancel</button>
        <button
          nz-button
          nzType="primary"
          [disabled]="loading || form.invalid"
          [nzLoading]="loading"
        >
          {{ initialQuestion ? "Update" : "Create" }}
        </button>
      </div>
    </form>
  `,
  styles: [
    `
      .flex {
        display: flex;
      }
      .justify-end {
        justify-content: flex-end;
      }
      .gap-2 {
        gap: 8px;
      }
      .mt-4 {
        margin-top: 16px;
      }
    `,
  ],
})
export class QuestionFormComponent implements OnInit, OnChanges {
  @Input() initialQuestion?: QuestionDto | null;
  @Input() loading = false;
  @Output() save = new EventEmitter<CreateQuestionPayload>();
  @Output() cancel = new EventEmitter<void>();

  private fb = inject(FormBuilder);
  private message = inject(NzMessageService);

  form!: FormGroup;
  tagsControl = this.fb.control<string[]>([]);

  multipleChoiceOptions: string[] = [];
  multipleChoiceCorrect: string[] = [];
  trueFalseAnswer = "true";
  fillBlankAnswer = "[]";
  orderingItems: string[] = [];
  matchingPairs: { left: string; right: string }[] = [];

  ngOnInit(): void {
    this.initForm();
    if (this.initialQuestion) this.populateForm();
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes["initialQuestion"] && !changes["initialQuestion"].firstChange) {
      this.populateForm();
    }
  }

  private initForm(): void {
    this.form = this.fb.group({
      content: ["", Validators.required],
      description: [""],
      type: ["multiple_choice", Validators.required],
      explanation: [""],
    });
    this.tagsControl.setValue([]);
  }

  private populateForm(): void {
    const q = this.initialQuestion!;
    this.form.patchValue({
      content: q.content,
      explanation: q.explanation || "",
      type: q.type,
    });
    this.tagsControl.setValue(q.tags || []);

    let metadata: any = {};
    if (q.metadataJson) {
      try {
        metadata = JSON.parse(q.metadataJson);
      } catch {}
    }
    this.form.patchValue({ description: metadata.description || "" });

    switch (q.type) {
      case "multiple_choice":
        this.multipleChoiceOptions = (metadata.options || []).map(
          (opt: any) => opt.text,
        );
        this.multipleChoiceCorrect = (metadata.options || [])
          .filter((opt: any) =>
            (metadata.correctAnswers || []).includes(opt.id),
          )
          .map((opt: any) => opt.text);
        break;
      case "true_false":
        this.trueFalseAnswer =
          metadata.correctAnswer === true ? "true" : "false";
        break;
      case "fill_blank":
        this.fillBlankAnswer = JSON.stringify(metadata.keywords || []);
        break;
      case "ordering":
        this.orderingItems = (metadata.items || []).map(
          (item: any) => item.text,
        );
        break;
      case "matching":
        this.matchingPairs = (metadata.pairs || []).map((p: any) => ({
          left: p.left,
          right: p.right,
        }));
        break;
    }
  }

  onTypeChange(newType: string): void {
    if (newType === "multiple_choice") {
      this.multipleChoiceOptions = ["", "", "", ""];
      this.multipleChoiceCorrect = [];
      this.trueFalseAnswer = "true";
      this.fillBlankAnswer = "[]";
      this.orderingItems = [];
      this.matchingPairs = [];
    } else if (newType === "true_false") {
      this.trueFalseAnswer = "true";
    } else if (newType === "fill_blank") {
      this.fillBlankAnswer = "[]";
    } else if (newType === "ordering") {
      this.orderingItems = ["", "", "", ""];
    } else if (newType === "matching") {
      this.matchingPairs = [
        { left: "", right: "" },
        { left: "", right: "" },
        { left: "", right: "" },
        { left: "", right: "" },
      ];
    }
  }

  setMultipleChoiceOptions(opts: string[]): void {
    this.multipleChoiceOptions = opts;
  }

  setMultipleChoiceCorrect(correct: string[]): void {
    this.multipleChoiceCorrect = correct;
  }

  buildMetadata(): any {
    const metadata: any = {};
    const desc = this.form.get("description")?.value?.trim();
    if (desc) metadata.description = desc;

    const type = this.form.get("type")?.value;
    switch (type) {
      case "multiple_choice": {
        const options = this.multipleChoiceOptions.filter((opt) => opt.trim());
        metadata.options = options.map((text, idx) => ({
          id: idx.toString(),
          text: text.trim(),
        }));
        const correctTexts = this.multipleChoiceCorrect.filter((ans) =>
          ans.trim(),
        );
        metadata.correctAnswers = metadata.options
          .filter((opt: any) => correctTexts.includes(opt.text))
          .map((opt: any) => opt.id);
        break;
      }
      case "true_false":
        metadata.correctAnswer = this.trueFalseAnswer === "true";
        break;
      case "fill_blank": {
        let keywords: string[] = [];
        try {
          keywords = JSON.parse(this.fillBlankAnswer);
        } catch {}
        metadata.keywords = keywords.filter((k) => k.trim());
        break;
      }
      case "ordering":
        metadata.items = this.orderingItems
          .filter((item) => item.trim())
          .map((text, idx) => ({ order_id: idx + 1, text: text.trim() }));
        break;
      case "matching":
        metadata.pairs = this.matchingPairs
          .filter((p) => p.left.trim() || p.right.trim())
          .map((p, idx) => ({
            id: idx + 1,
            left: p.left.trim(),
            right: p.right.trim(),
          }));
        break;
    }
    return metadata;
  }

  onSubmit(): void {
    const content = this.form.get("content")?.value?.trim();
    if (!content) {
      this.message.warning("Title is required");
      return;
    }

    const type = this.form.get("type")?.value;
    if (type === "multiple_choice") {
      const nonEmpty = this.multipleChoiceOptions.filter((opt) => opt.trim());
      if (nonEmpty.length < 2) {
        this.message.warning("At least two options are required");
        return;
      }
      if (this.multipleChoiceCorrect.length === 0) {
        this.message.warning("Please select at least one correct answer");
        return;
      }
    }

    if (type === "fill_blank") {
      try {
        const keywords = JSON.parse(this.fillBlankAnswer);
        if (!Array.isArray(keywords) || keywords.length === 0) {
          this.message.warning("Please enter at least one keyword");
          return;
        }
        if (keywords.some((k: string) => k.includes(" "))) {
          this.message.warning(
            "Keywords must be single words (no spaces allowed)",
          );
          return;
        }
      } catch {
        this.message.warning("Invalid keyword format");
        return;
      }
    }

    const metadata = this.buildMetadata();
    const payload: CreateQuestionPayload = {
      type,
      content,
      explanation: this.form.get("explanation")?.value?.trim() || undefined,
      metadataJson: Object.keys(metadata).length
        ? JSON.stringify(metadata)
        : undefined,
      tagNames: this.tagsControl.value?.length
        ? this.tagsControl.value
        : undefined,
    };
    this.save.emit(payload);
  }

  onCancel(): void {
    this.cancel.emit();
  }
}

// slp/frontend-vue/src/features/question/components/QuestionForm.vue
<template>
  <a-form :model="form" @submit.prevent="handleSubmit" layout="vertical">
    <!-- Common fields -->
    <a-form-item label="Question Title" required>
      <a-input
        v-model:value="form.title"
        placeholder="Enter the question"
        data-testid="question-title"
      />
    </a-form-item>

    <a-form-item label="Description / Details">
      <a-textarea
        v-model:value="form.description"
        placeholder="Additional context"
        :rows="2"
        data-testid="question-description"
      />
    </a-form-item>

    <a-form-item
      label="Question Type"
      required
      data-testid="form-item-question-type"
    >
      <a-select
        v-model:value="form.type"
        placeholder="Select type"
        data-testid="question-type-select"
      >
        <a-select-option
          value="multiple_choice"
          data-testid="option-multiple-choice"
        >
          Multiple Choice
        </a-select-option>
        <a-select-option value="true_false" data-testid="option-true-false">
          True/False
        </a-select-option>
        <a-select-option value="fill_blank" data-testid="option-fill-blank">
          Fill Blank
        </a-select-option>
        <a-select-option value="ordering" data-testid="option-ordering">
          Ordering
        </a-select-option>
        <a-select-option value="matching" data-testid="option-matching">
          Matching
        </a-select-option>
      </a-select>
    </a-form-item>

    <!-- Type-specific fields -->
    <template v-if="form.type === 'multiple_choice'">
      <MultipleChoice
        v-model:model-value="form.options"
        v-model:correct-answers="form.correctAnswers"
      />
    </template>

    <template v-else-if="form.type === 'true_false'">
      <TrueFalse v-model:answer="form.answer" />
    </template>

    <template v-else-if="form.type === 'fill_blank'">
      <FillBlank v-model:answer="form.answer" :question-title="form.title" />
    </template>

    <template v-else-if="form.type === 'ordering'">
      <Ordering v-model:model-value="form.orderingItems" />
    </template>

    <template v-else-if="form.type === 'matching'">
      <Matching v-model:model-value="form.matchingPairs" />
    </template>

    <!-- Explanation -->
    <a-form-item label="Explanation">
      <a-textarea
        v-model:value="form.explanation"
        placeholder="Why this answer is correct"
        :rows="2"
        data-testid="question-explanation"
      />
    </a-form-item>

    <!-- Tags — replaced with TagSelector -->
    <a-form-item label="Tags">
      <TagSelector v-model="form.tags" data-testid="question-tags" />
    </a-form-item>

    <a-form-item>
      <div class="flex gap-2">
        <a-button @click="handleCancel" block>Cancel</a-button>
        <a-button
          type="primary"
          html-type="submit"
          :loading="loading"
          block
          data-testid="submit-question"
        >
          {{ isEdit ? "Update Question" : "Create Question" }}
        </a-button>
      </div>
    </a-form-item>
  </a-form>
</template>

<script setup lang="ts">
import { ref, watch } from "vue";
import { message } from "ant-design-vue";
import MultipleChoice from "./MultipleChoice.vue";
import TrueFalse from "./TrueFalse.vue";
import FillBlank from "./FillBlank.vue";
import Ordering from "./Ordering.vue";
import Matching from "./Matching.vue";
import TagSelector from "@/components/TagSelector.vue";
import type {
  QuestionDto,
  CreateQuestionPayload,
} from "../stores/questionStore";

const props = defineProps<{
  initialQuestion?: Partial<QuestionDto> | null;
  loading?: boolean;
}>();

const emit = defineEmits<{
  (e: "save", payload: CreateQuestionPayload): void;
  (e: "cancel"): void;
}>();

const isEdit = ref(!!props.initialQuestion?.id);

interface QuestionForm {
  title: string;
  description: string;
  type: CreateQuestionPayload["type"];
  options: string[];
  correctAnswers: string[];
  answer: string;
  explanation: string;
  orderingItems: string[];
  matchingPairs: { left: string; right: string }[];
  tags: string[];
}

const getDefaultForm = (): QuestionForm => ({
  title: "",
  description: "",
  type: "multiple_choice",
  options: ["", "", "", ""],
  correctAnswers: [],
  answer: "",
  explanation: "",
  orderingItems: ["", "", "", ""],
  matchingPairs: [
    { left: "", right: "" },
    { left: "", right: "" },
    { left: "", right: "" },
    { left: "", right: "" },
  ],
  tags: [],
});

const form = ref<QuestionForm>(getDefaultForm());

const resetForm = () => {
  form.value = getDefaultForm();
};

const initializeForm = () => {
  if (!props.initialQuestion) return;

  const q = props.initialQuestion;
  form.value.title = q.content || "";
  form.value.type = (q.type as any) || "multiple_choice";
  form.value.explanation = q.explanation || "";
  form.value.tags = q.tags || [];

  let metadata: any = {};
  if (q.metadataJson) {
    try {
      metadata = JSON.parse(q.metadataJson);
    } catch {
      metadata = {};
    }
  }

  form.value.description = metadata.description || "";

  switch (q.type) {
    case "multiple_choice": {
      const options = (metadata.options || []).map((opt: any) => opt.text);
      form.value.options = options.length ? options : ["", "", "", ""];
      const correctIds = metadata.correctAnswers || [];
      form.value.correctAnswers = (metadata.options || [])
        .filter((opt: any) => correctIds.includes(opt.id))
        .map((opt: any) => opt.text);
      break;
    }
    case "true_false":
      form.value.answer = metadata.correctAnswer === true ? "true" : "false";
      break;
    case "fill_blank":
      form.value.answer = JSON.stringify(metadata.keywords || []);
      break;
    case "ordering": {
      const items = (metadata.items || []).map((item: any) => item.text);
      form.value.orderingItems = items.length ? items : ["", "", "", ""];
      break;
    }
    case "matching": {
      const pairs = (metadata.pairs || []).map((p: any) => ({
        left: p.left,
        right: p.right,
      }));
      form.value.matchingPairs = pairs.length
        ? pairs
        : [
            { left: "", right: "" },
            { left: "", right: "" },
            { left: "", right: "" },
            { left: "", right: "" },
          ];
      break;
    }
  }
};

watch(
  () => props.initialQuestion,
  (newVal) => {
    if (newVal) {
      isEdit.value = true;
      initializeForm();
    } else {
      isEdit.value = false;
      resetForm();
    }
  },
  { immediate: true },
);

watch(
  () => form.value.type,
  (newType) => {
    if (newType === "multiple_choice") {
      form.value.options = ["", "", "", ""];
      form.value.correctAnswers = [];
      form.value.answer = "";
    } else if (newType === "true_false") {
      form.value.answer = "true";
    } else if (newType === "fill_blank") {
      form.value.answer = "[]";
    } else if (newType === "ordering") {
      form.value.orderingItems = ["", "", "", ""];
    } else if (newType === "matching") {
      form.value.matchingPairs = [
        { left: "", right: "" },
        { left: "", right: "" },
        { left: "", right: "" },
        { left: "", right: "" },
      ];
    }
  },
);

function buildMetadata(): Record<string, any> {
  const metadata: Record<string, any> = {};
  if (form.value.description.trim())
    metadata.description = form.value.description.trim();

  switch (form.value.type) {
    case "multiple_choice": {
      const options = form.value.options.filter((opt) => opt.trim() !== "");
      metadata.options = options.map((text, idx) => ({
        id: idx.toString(),
        text: text.trim(),
      }));
      const correctTexts = form.value.correctAnswers.filter(
        (ans) => ans.trim() !== "",
      );
      metadata.correctAnswers = metadata.options
        .filter((opt: { text: string }) => correctTexts.includes(opt.text))
        .map((opt: { id: any }) => opt.id);
      break;
    }
    case "true_false":
      metadata.correctAnswer = form.value.answer === "true";
      break;
    case "fill_blank": {
      let keywords: string[] = [];
      try {
        keywords = JSON.parse(form.value.answer);
      } catch {
        keywords = [];
      }
      metadata.keywords = keywords.filter((k: string) => k.trim() !== "");
      break;
    }
    case "ordering": {
      metadata.items = form.value.orderingItems
        .filter((item) => item.trim() !== "")
        .map((text, idx) => ({ order_id: idx + 1, text: text.trim() }));
      break;
    }
    case "matching": {
      metadata.pairs = form.value.matchingPairs
        .filter((p) => p.left.trim() !== "" || p.right.trim() !== "")
        .map((p, idx) => ({
          id: idx + 1,
          left: p.left.trim(),
          right: p.right.trim(),
        }));
      break;
    }
  }
  return metadata;
}

const handleSubmit = () => {
  if (!form.value.title.trim()) {
    message.warning("Title is required");
    return;
  }

  if (form.value.type === "multiple_choice") {
    const nonEmpty = form.value.options.filter((opt) => opt.trim() !== "");
    if (nonEmpty.length < 2) {
      message.warning("At least two options are required");
      return;
    }
    if (form.value.correctAnswers.length === 0) {
      message.warning("Please select at least one correct answer");
      return;
    }
  }

  if (form.value.type === "fill_blank") {
    try {
      const keywords = JSON.parse(form.value.answer);
      if (!Array.isArray(keywords) || keywords.length === 0) {
        message.warning("Please enter at least one keyword");
        return;
      }
      if (keywords.some((k: string) => k.includes(" "))) {
        message.warning("Keywords must be single words (no spaces allowed)");
        return;
      }
    } catch {
      message.warning("Invalid keyword format");
      return;
    }
  }

  const metadata = buildMetadata();
  const payload: CreateQuestionPayload = {
    type: form.value.type,
    content: form.value.title.trim(),
    explanation: form.value.explanation.trim() || undefined,
    metadataJson: Object.keys(metadata).length
      ? JSON.stringify(metadata)
      : undefined,
    tagNames: form.value.tags.length ? form.value.tags : undefined,
  };

  emit("save", payload);
};

const handleCancel = () => emit("cancel");
</script>
