// slp/frontend-vue/src/features/admin/pages/AdminHealthPage.vue
<template>
  <MobileLayout title="Service Health">
    <div class="space-y-4">
      <a-card data-testid="health-card">
        <div class="flex justify-between items-center mb-4">
          <h2 class="text-lg font-semibold">System Services</h2>
          <a-button
            type="primary"
            @click="refresh"
            :loading="loading"
            data-testid="refresh-button"
          >
            Refresh
          </a-button>
        </div>
        <a-table
          :columns="columns"
          :data-source="services"
          :pagination="false"
          :loading="loading"
          row-key="name"
          data-testid="services-table"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'status'">
              <a-tag :color="statusColor(record.status)">
                {{ record.status }}
              </a-tag>
            </template>
            <template v-else-if="column.key === 'responseTimeMs'">
              {{ record.responseTimeMs }} ms
            </template>
          </template>
        </a-table>
        <div class="mt-4 text-xs text-gray-500" data-testid="last-updated">
          Last updated:
          {{ timestamp ? new Date(timestamp).toLocaleString() : "—" }}
        </div>
      </a-card>
    </div>
  </MobileLayout>
</template>

<script setup lang="ts">
import { ref, onMounted } from "vue";
import { message } from "ant-design-vue";
import MobileLayout from "@/layouts/MobileLayout.vue";
import apiClient from "@/lib/api/client";

interface ServiceHealth {
  name: string;
  status: string;
  details?: string;
  responseTimeMs: number;
}

const loading = ref(false);
const services = ref<ServiceHealth[]>([]);
const timestamp = ref<string | null>(null);

const columns = [
  { title: "Service", dataIndex: "name", key: "name" },
  { title: "Status", dataIndex: "status", key: "status" },
  { title: "Details", dataIndex: "details", key: "details", ellipsis: true },
  {
    title: "Response Time",
    dataIndex: "responseTimeMs",
    key: "responseTimeMs",
  },
];

const statusColor = (status: string) => {
  switch (status) {
    case "Healthy":
      return "green";
    case "Degraded":
      return "orange";
    default:
      return "red";
  }
};

const fetchHealth = async () => {
  loading.value = true;
  try {
    const response = await apiClient.get("/HealthDashboard/services");
    services.value = response.data.services;
    timestamp.value = response.data.timestamp;
  } catch (error) {
    message.error("Failed to load health status");
    console.error(error);
  } finally {
    loading.value = false;
  }
};

const refresh = () => {
  fetchHealth();
};

onMounted(() => {
  fetchHealth();
});
</script>

// slp/frontend-angular/src/features/admin/pages/admin-health-page.component.ts
import { Component, OnInit, inject, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { NzCardModule } from "ng-zorro-antd/card";
import { NzTableModule } from "ng-zorro-antd/table";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzTagModule } from "ng-zorro-antd/tag";
import { NzSpinModule } from "ng-zorro-antd/spin";
import { NzMessageService } from "ng-zorro-antd/message";
import { ApiClientService } from "../../../services/api-client.service";

interface ServiceHealth {
  name: string;
  status: string;
  details?: string;
  responseTimeMs: number;
}

@Component({
  selector: "app-admin-health-page",
  standalone: true,
  imports: [
    CommonModule,
    NzCardModule,
    NzTableModule,
    NzButtonModule,
    NzTagModule,
    NzSpinModule,
  ],
  template: `
    <div>
      <nz-card data-testid="health-card">
        <div class="flex justify-between items-center mb-4">
          <h2 class="text-lg font-semibold">System Services</h2>
          <button
            nz-button
            nzType="primary"
            data-testid="refresh-button"
            (click)="refresh()"
            [nzLoading]="loading()"
          >
            Refresh
          </button>
        </div>
        <nz-table
          data-testid="services-table"
          [nzData]="services()"
          [nzLoading]="loading()"
          [nzShowPagination]="false"
        >
          <thead>
            <tr>
              <th>Service</th>
              <th>Status</th>
              <th>Details</th>
              <th>Response Time</th>
            </tr>
          </thead>
          <tbody>
            @for (s of services(); track s.name) {
              <tr>
                <td>{{ s.name }}</td>
                <td>
                  <nz-tag [nzColor]="statusColor(s.status)">{{
                    s.status
                  }}</nz-tag>
                </td>
                <td>{{ s.details }}</td>
                <td>{{ s.responseTimeMs }} ms</td>
              </tr>
            }
          </tbody>
        </nz-table>
        <div data-testid="last-updated" class="mt-4 text-xs text-gray-500">
          Last updated: {{ timestamp() ? (timestamp() | date: "medium") : "—" }}
        </div>
      </nz-card>
    </div>
  `,
})
export class AdminHealthPageComponent implements OnInit {
  private api = inject(ApiClientService);
  private message = inject(NzMessageService);
  services = signal<ServiceHealth[]>([]);
  timestamp = signal<string | null>(null);
  loading = signal(false);

  ngOnInit() {
    this.fetchHealth();
  }

  async fetchHealth() {
    this.loading.set(true);
    try {
      const res: any = await this.api
        .get("/HealthDashboard/services")
        .toPromise();
      this.services.set(res.services);
      this.timestamp.set(res.timestamp);
    } catch {
      this.message.error("Failed to load health status");
    } finally {
      this.loading.set(false);
    }
  }

  refresh() {
    this.fetchHealth();
  }

  statusColor(status: string): string {
    switch (status) {
      case "Healthy":
        return "green";
      case "Degraded":
        return "orange";
      default:
        return "red";
    }
  }
}
