// slp/frontend-angular/src/layouts/right-sidebar/right-sidebar.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Router } from "@angular/router";
import { NzIconModule } from "ng-zorro-antd/icon";
import { NzMenuModule } from "ng-zorro-antd/menu";
import { NzModalModule } from "ng-zorro-antd/modal";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzMessageService } from "ng-zorro-antd/message";
import { TranslateModule, TranslateService } from "@ngx-translate/core";
import { AuthService } from "../../features/auth/auth.service";
import {
  Language,
  SettingsService,
  Theme,
} from "../../services/settings.service";
import { Observable, map } from "rxjs";
import { RouterModule } from "@angular/router"; // 1. Import this

@Component({
  selector: "app-right-sidebar",
  standalone: true,
  imports: [
    CommonModule,
    NzIconModule,
    NzMenuModule,
    NzModalModule,
    NzButtonModule,
    TranslateModule,
    RouterModule,
  ],
  templateUrl: "./right-sidebar.component.html",
  styleUrls: ["./right-sidebar.component.scss"],
})
export class RightSidebarComponent implements OnInit {
  @Input() isOpen = false;
  @Output() close = new EventEmitter<void>();
  @Output() logout = new EventEmitter<void>();

  user$: Observable<any>;
  isAdmin$: Observable<boolean>;
  sendingVerification = false;
  settingsVisible = false;

  // Explicitly type the array so the 'value' is seen as Theme, not just string
  themeOptions: { value: Theme; label: string; icon: string }[] = [
    { value: "light", label: "settings.themeLight", icon: "sun" },
    { value: "dark", label: "settings.themeDark", icon: "moon" },
  ];

  // Do the same for languageOptions to prevent the next error!
  languageOptions: { value: Language; label: string; flag: string }[] = [
    { value: "en", label: "English", flag: "🇬🇧" },
    { value: "vi", label: "Tiếng Việt", flag: "🇻🇳" },
  ];

  constructor(
    private authService: AuthService,
    public settingsService: SettingsService,
    public translateService: TranslateService,
    private message: NzMessageService,
    private router: Router,
  ) {
    this.user$ = this.authService.user$;
    this.isAdmin$ = this.user$.pipe(map((user) => user?.role === "admin"));
  }

  ngOnInit(): void {
    // sync language from settings
    this.translateService.use(this.settingsService.language());
  }

  closeSidebar(): void {
    this.close.emit();
  }

  onLogoutClick(): void {
    this.logout.emit();
    this.closeSidebar();
  }

  openSettings(): void {
    this.settingsVisible = true;
  }

  sendVerification(): void {
    this.sendingVerification = true;
    this.authService.sendVerificationEmail().subscribe({
      next: () => {
        this.message.success(
          this.translateService.instant("auth.verificationEmailSent"),
        );
        this.sendingVerification = false;
      },
      error: () => {
        this.message.error(this.translateService.instant("common.error"));
        this.sendingVerification = false;
      },
    });
  }

  changeLanguage(lang: Language): void {
    this.settingsService.setLanguage(lang);
    this.translateService.use(lang);
  }
}

<div
  class="fixed top-0 right-0 h-screen w-64 bg-white shadow-lg transform transition-transform duration-300 z-50"
  [class.translate-x-0]="isOpen"
  [class.translate-x-full]="!isOpen"
>
  <div class="flex flex-col h-full">
    <div class="p-4 border-b flex justify-between items-center">
      <h2 class="font-semibold">{{ "nav.menu" | translate }}</h2>
      <button (click)="closeSidebar()" class="p-2">
        <i nz-icon nzType="close" nzTheme="outline"></i>
      </button>
    </div>

    <div *ngIf="user$ | async as user" class="p-4 border-b">
      <div class="flex items-center space-x-3">
        <div
          class="w-10 h-10 rounded-full bg-blue-500 flex items-center justify-center text-white font-semibold"
        >
          {{ user.username.charAt(0).toUpperCase() }}
        </div>
        <div class="flex-1 min-w-0">
          <p class="font-medium truncate">{{ user.username }}</p>
          <p class="text-sm text-gray-500 truncate">{{ user.email }}</p>
        </div>
      </div>
      <div *ngIf="!user.emailVerified" class="mt-2">
        <button
          nz-button
          nzType="link"
          size="small"
          (click)="sendVerification()"
          [nzLoading]="sendingVerification"
        >
          {{ "auth.verifyEmail" | translate }}
        </button>
      </div>
    </div>

    <div class="flex-1 overflow-y-auto p-2">
      <ul nz-menu nzMode="inline" class="border-none">
        <li nz-menu-item nzMatchRouter [routerLink]="'/dashboard'">
          <i nz-icon nzType="dashboard" nzTheme="outline"></i>
          <span>{{ "nav.dashboard" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/quiz'">
          <i nz-icon nzType="file-text" nzTheme="outline"></i>
          <span>{{ "nav.myQuizzes" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/quiz/new'">
          <i nz-icon nzType="plus-circle" nzTheme="outline"></i>
          <span>{{ "nav.createQuiz" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/questions'">
          <i nz-icon nzType="question-circle" nzTheme="outline"></i>
          <span>{{ "nav.questionBank" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/question/new'">
          <i nz-icon nzType="plus" nzTheme="outline"></i>
          <span>{{ "nav.newQuestion" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/source'">
          <i nz-icon nzType="folder-open" nzTheme="outline"></i>
          <span>{{ "nav.mySources" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/source/upload'">
          <i nz-icon nzType="upload" nzTheme="outline"></i>
          <span>{{ "nav.uploadFile" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/source/new-url'">
          <i nz-icon nzType="link" nzTheme="outline"></i>
          <span>{{ "nav.addFromUrl" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/source/new-text'">
          <i nz-icon nzType="file-text" nzTheme="outline"></i>
          <span>{{ "nav.addFromText" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/notes'">
          <i nz-icon nzType="file-text" nzTheme="outline"></i>
          <span>{{ "nav.myNotes" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/favourites'">
          <i nz-icon nzType="star" nzTheme="outline"></i>
          <span>{{ "nav.favourites" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/search'">
          <i nz-icon nzType="search" nzTheme="outline"></i>
          <span>{{ "nav.search" | translate }}</span>
        </li>

        <li nz-menu-divider></li>

        <li nz-menu-item nzMatchRouter [routerLink]="'/profile'">
          <i nz-icon nzType="user" nzTheme="outline"></i>
          <span>{{ "nav.profile" | translate }}</span>
        </li>
        <li nz-menu-item nzMatchRouter [routerLink]="'/reports'">
          <i nz-icon nzType="flag" nzTheme="outline"></i>
          <span>{{ "nav.reports" | translate }}</span>
        </li>

        <li
          *ngIf="isAdmin$ | async"
          nz-menu-item
          nzMatchRouter
          [routerLink]="'/admin'"
        >
          <i nz-icon nzType="security-scan" nzTheme="outline"></i>
          <span>{{ "nav.admin" | translate }}</span>
        </li>

        <li nz-menu-divider></li>

        <li nz-menu-item (click)="openSettings()">
          <i nz-icon nzType="setting" nzTheme="outline"></i>
          <span>{{ "settings.title" | translate }}</span>
        </li>
        <li nz-menu-item (click)="onLogoutClick()" class="text-red-500">
          <i nz-icon nzType="logout" nzTheme="outline"></i>
          <span>{{ "auth.logout" | translate }}</span>
        </li>
      </ul>
    </div>
  </div>
</div>

<div
  *ngIf="isOpen"
  class="fixed inset-0 bg-black bg-opacity-50 z-40"
  (click)="closeSidebar()"
></div>

<!-- Settings Modal -->
<nz-modal
  [(nzVisible)]="settingsVisible"
  nzTitle="{{ 'settings.title' | translate }}"
  [nzFooter]="null"
  nzWidth="320px"
  nzCentered
>
  <div class="space-y-6 py-2">
    <div>
      <p class="text-sm font-medium text-gray-600 mb-2">
        {{ "settings.theme" | translate }}
      </p>
      <div class="flex gap-2">
        <button
          *ngFor="let themeOption of themeOptions"
          class="..."
          [class.border-blue-500]="
            settingsService.theme() === themeOption.value
          "
          [class.bg-blue-50]="settingsService.theme() === themeOption.value"
          (click)="settingsService.setTheme(themeOption.value)"
        >
          <i nz-icon [nzType]="themeOption.icon"></i>
          {{ themeOption.label | translate }}
        </button>
      </div>
    </div>
    <div>
      <p class="text-sm font-medium text-gray-600 mb-2">
        {{ "settings.language" | translate }}
      </p>
      <div class="flex gap-2">
        <button
          *ngFor="let lang of languageOptions"
          class="flex-1 flex items-center justify-center gap-2 py-2 px-3 rounded-lg border text-sm font-medium transition-all"
          [class.border-blue-500]="translateService.currentLang === lang.value"
          [class.bg-blue-50]="translateService.currentLang === lang.value"
          [class.text-blue-600]="translateService.currentLang === lang.value"
          [class.border-gray-200]="translateService.currentLang !== lang.value"
          [class.text-gray-600]="translateService.currentLang !== lang.value"
          (click)="changeLanguage(lang.value)"
        >
          <span>{{ lang.flag }}</span>
          {{ lang.label | translate }}
        </button>
      </div>
    </div>
  </div>
</nz-modal>

// slp/frontend-vue/src/layouts/RightSidebar.vue
<template>
  <div
    class="fixed top-0 right-0 h-screen w-64 bg-white shadow-lg transform transition-transform duration-300 z-50"
    :class="{ 'translate-x-0': isOpen, 'translate-x-full': !isOpen }"
  >
    <div class="flex flex-col h-full">
      <!-- Header -->
      <div class="p-4 border-b flex justify-between items-center">
        <h2 class="font-semibold">Menu</h2>
        <button @click="$emit('close')" class="p-2">
          <X :size="20" />
        </button>
      </div>

      <!-- User Info -->
      <div v-if="authStore.user" class="p-4 border-b">
        <div class="flex items-center space-x-3">
          <div
            class="w-10 h-10 rounded-full bg-blue-500 flex items-center justify-center text-white font-semibold"
          >
            {{ authStore.user.username.charAt(0).toUpperCase() }}
          </div>
          <div class="flex-1 min-w-0">
            <p class="font-medium truncate">{{ authStore.user.username }}</p>
            <p class="text-sm text-gray-500 truncate">
              {{ authStore.user.email }}
            </p>
          </div>
        </div>
        <div v-if="!authStore.isEmailVerified" class="mt-2">
          <a-button
            type="link"
            size="small"
            @click="sendVerification"
            :loading="sendingVerification"
          >
            Verify Email
          </a-button>
        </div>
      </div>

      <!-- Navigation -->
      <div class="flex-1 overflow-y-auto p-2">
        <a-menu
          mode="inline"
          :selected-keys="[currentRoute]"
          class="border-none"
        >
          <a-menu-item key="/dashboard">
            <router-link to="/dashboard" class="flex items-center">
              <LayoutDashboard :size="18" class="mr-2" />Dashboard
            </router-link>
          </a-menu-item>

          <a-menu-item key="/quiz">
            <router-link to="/quiz" class="flex items-center">
              <FileText :size="18" class="mr-2" />My Quizzes
            </router-link>
          </a-menu-item>
          <a-menu-item key="/quiz/new">
            <router-link to="/quiz/new" class="flex items-center">
              <PlusCircle :size="18" class="mr-2" />Create Quiz
            </router-link>
          </a-menu-item>

          <a-menu-item key="/questions">
            <router-link to="/questions" class="flex items-center">
              <HelpCircle :size="18" class="mr-2" />Question Bank
            </router-link>
          </a-menu-item>
          <a-menu-item key="/question/new">
            <router-link to="/question/new" class="flex items-center">
              <Plus :size="18" class="mr-2" />New Question
            </router-link>
          </a-menu-item>

          <a-menu-item key="/source">
            <router-link to="/source" class="flex items-center">
              <FolderOpen :size="18" class="mr-2" />My Sources
            </router-link>
          </a-menu-item>
          <a-menu-item key="/source/upload">
            <router-link to="/source/upload" class="flex items-center">
              <Upload :size="18" class="mr-2" />Upload File
            </router-link>
          </a-menu-item>
          <a-menu-item key="/source/new-url">
            <router-link to="/source/new-url" class="flex items-center">
              <LinkIcon :size="18" class="mr-2" />Add from URL
            </router-link>
          </a-menu-item>
          <a-menu-item key="/source/new-note">
            <router-link to="/source/new-note" class="flex items-center">
              <FileText :size="18" class="mr-2" />Add from Text
            </router-link>
          </a-menu-item>

          <a-menu-item key="/search">
            <router-link to="/search" class="flex items-center">
              <Search :size="18" class="mr-2" />Search
            </router-link>
          </a-menu-item>

          <a-menu-divider />

          <a-menu-item key="/profile">
            <router-link to="/profile" class="flex items-center">
              <User :size="18" class="mr-2" />Profile
            </router-link>
          </a-menu-item>

          <a-menu-item key="/reports">
            <router-link to="/reports" class="flex items-center">
              <Flag :size="18" class="mr-2" />My Reports
            </router-link>
          </a-menu-item>

          <a-menu-item v-if="authStore.isAdmin" key="/admin">
            <router-link to="/admin" class="flex items-center">
              <Shield :size="18" class="mr-2" />Admin
            </router-link>
          </a-menu-item>

          <a-menu-item v-if="authStore.isAdmin" key="/admin/health">
            <router-link to="/admin/health" class="flex items-center">
              <Activity :size="18" class="mr-2" />Service Health
            </router-link>
          </a-menu-item>

          <a-menu-divider />

          <!-- Settings -->
          <a-menu-item key="settings" @click="settingsOpen = true">
            <div class="flex items-center">
              <Settings :size="18" class="mr-2" />Settings
            </div>
          </a-menu-item>

          <!-- Logout -->
          <a-menu-item key="logout" @click="handleLogout">
            <div class="flex items-center text-red-500">
              <LogOut :size="18" class="mr-2" />Logout
            </div>
          </a-menu-item>
        </a-menu>
      </div>
    </div>
  </div>

  <!-- Overlay -->
  <div
    v-if="isOpen"
    class="fixed inset-0 bg-black bg-opacity-50 z-40"
    @click="$emit('close')"
  />

  <!-- ── Settings Modal ──────────────────────────────────────────────────── -->
  <a-modal
    v-model:open="settingsOpen"
    title="Settings"
    :footer="null"
    width="320px"
    centered
  >
    <div class="space-y-6 py-2">
      <!-- Theme -->
      <div>
        <p class="text-sm font-medium text-gray-600 mb-2">Theme</p>
        <div class="flex gap-2">
          <button
            v-for="option in themeOptions"
            :key="option.value"
            class="flex-1 flex items-center justify-center gap-2 py-2 px-3 rounded-lg border text-sm font-medium transition-all"
            :class="
              settingsStore.theme === option.value
                ? 'border-blue-500 bg-blue-50 text-blue-600'
                : 'border-gray-200 text-gray-600 hover:border-gray-300'
            "
            @click="settingsStore.setTheme(option.value)"
          >
            <component :is="option.icon" :size="16" />
            {{ option.label }}
          </button>
        </div>
      </div>

      <!-- Language -->
      <div>
        <p class="text-sm font-medium text-gray-600 mb-2">Language</p>
        <div class="flex gap-2">
          <button
            v-for="option in languageOptions"
            :key="option.value"
            class="flex-1 flex items-center justify-center gap-2 py-2 px-3 rounded-lg border text-sm font-medium transition-all"
            :class="
              settingsStore.language === option.value
                ? 'border-blue-500 bg-blue-50 text-blue-600'
                : 'border-gray-200 text-gray-600 hover:border-gray-300'
            "
            @click="settingsStore.setLanguage(option.value)"
          >
            <span>{{ option.flag }}</span>
            {{ option.label }}
          </button>
        </div>
      </div>
    </div>
  </a-modal>
</template>

<script setup lang="ts">
import { ref } from "vue";
import { useRoute } from "vue-router";
import { Menu, Divider, Button } from "ant-design-vue";
import {
  X,
  LayoutDashboard,
  User,
  Shield,
  LogOut,
  FileText,
  PlusCircle,
  HelpCircle,
  Plus,
  Upload,
  FolderOpen,
  Link as LinkIcon,
  Search,
  Settings,
  Sun,
  Moon,
  Flag,
  Activity
} from "lucide-vue-next";
import { useAuthStore } from "@/features/auth/stores/authStore";
import { useSettingsStore } from "@/features/settings/stores/settingsStore";
import type { Theme, Language } from "@/features/settings/stores/settingsStore";
import { message } from "ant-design-vue";

const AMenu = Menu;
const AMenuItem = Menu.Item;
const AMenuDivider = Divider;
const AButton = Button;

defineProps<{ isOpen: boolean }>();
const emit = defineEmits(["close", "logout"]);

const route = useRoute();
const authStore = useAuthStore();
const settingsStore = useSettingsStore();
const currentRoute = route.path;

const settingsOpen = ref(false);
const sendingVerification = ref(false);

// ── Option lists ──────────────────────────────────────────────────────────────
const themeOptions: { value: Theme; label: string; icon: any }[] = [
  { value: "light", label: "Light", icon: Sun },
  { value: "dark", label: "Dark", icon: Moon },
];

const languageOptions: { value: Language; label: string; flag: string }[] = [
  { value: "en", label: "English", flag: "🇬🇧" },
  { value: "vi", label: "Tiếng Việt", flag: "🇻🇳" },
];

// ── Handlers ──────────────────────────────────────────────────────────────────
const handleLogout = async () => {
  await authStore.logout();
  emit("logout");
  emit("close");
};

const sendVerification = async () => {
  sendingVerification.value = true;
  const success = await authStore.sendVerificationEmail();
  sendingVerification.value = false;
  if (success) message.success("Verification email sent!");
  else message.error("Failed to send verification email");
};
</script>
