// slp/frontend-angular/src/app/features/auth/pages/register/register.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzFormModule } from 'ng-zorro-antd/form';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzAlertModule } from 'ng-zorro-antd/alert';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzMessageService } from 'ng-zorro-antd/message';
import { AuthService } from '../../../../core/services/auth.service';
import { firstValueFrom } from 'rxjs';

@Component({
  selector: 'app-register',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    RouterModule,
    NzCardModule,
    NzFormModule,
    NzInputModule,
    NzButtonModule,
    NzAlertModule,
    NzIconModule
  ],
  templateUrl: './register.component.html',
})
export class RegisterComponent {
  public authService = inject(AuthService);
  public router = inject(Router);
  private message = inject(NzMessageService);

  form = {
    username: '',
    email: '',
    password: '',
    confirmPassword: ''
  };

  loading$ = this.authService.loading$;
  error$ = this.authService.error$;

  async handleRegister(): Promise<void> {
    if (this.form.password !== this.form.confirmPassword) {
      this.message.error('Passwords do not match');
      return;
    }

    try {
      const success = await firstValueFrom(
        this.authService.register(this.form.username, this.form.email, this.form.password)
      );
      if (success) {
        this.message.success('Registration successful! Please login.');
        this.router.navigate(['/login']);
      }
    } catch {
      // Error already handled by service
    }
  }
}
<div class="min-h-screen bg-linear-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
  <nz-card class="w-full max-w-md">
    <div class="text-center mb-8">
      <h1 class="text-2xl font-bold text-gray-900">Create Account</h1>
      <p class="text-gray-600 mt-2">Sign up to get started</p>
    </div>

    <form nz-form (ngSubmit)="handleRegister()" layout="vertical">
      <nz-form-item>
        <nz-form-label>Username</nz-form-label>
        <nz-form-control>
          <nz-input-group nzPrefixIcon="user">
            <input
              nz-input
              [(ngModel)]="form.username"
              name="username"
              placeholder="Choose a username"
            />
          </nz-input-group>
        </nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label>Email</nz-form-label>
        <nz-form-control>
          <nz-input-group nzPrefixIcon="mail">
            <input
              nz-input
              type="email"
              [(ngModel)]="form.email"
              name="email"
              placeholder="Enter your email"
            />
          </nz-input-group>
        </nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label>Password</nz-form-label>
        <nz-form-control>
          <nz-input-group nzPrefixIcon="lock">
            <input
              nz-input
              type="password"
              [(ngModel)]="form.password"
              name="password"
              placeholder="Create a password"
            />
          </nz-input-group>
        </nz-form-control>
      </nz-form-item>

      <nz-form-item>
        <nz-form-label>Confirm Password</nz-form-label>
        <nz-form-control>
          <nz-input-group nzPrefixIcon="lock">
            <input
              nz-input
              type="password"
              [(ngModel)]="form.confirmPassword"
              name="confirmPassword"
              placeholder="Confirm your password"
            />
          </nz-input-group>
        </nz-form-control>
      </nz-form-item>

      <button
        nz-button
        nzType="primary"
        [nzLoading]="(loading$ | async)!"
        block
        nzSize="large"
        class="mb-4"
      >
        Sign Up
      </button>

      <div class="text-center">
        <span class="text-gray-600">Already have an account? </span>
        <a routerLink="/login" class="text-blue-600 hover:text-blue-700">
          Sign in
        </a>
      </div>

      <nz-alert
        *ngIf="(error$ | async) as error"
        [nzMessage]="error"
        nzType="error"
        nzShowIcon
        [nzCloseable]="true"
        (nzOnClose)="authService.clearError()"
        class="mt-4"
      />
    </form>
  </nz-card>
</div>

// slp/frontend-vue/src/views/Register.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center p-4">
    <a-card class="w-full max-w-md">
      <div class="text-center mb-8">
        <h1 class="text-2xl font-bold text-gray-900">Create Account</h1>
        <p class="text-gray-600 mt-2">Sign up to get started</p>
      </div>

      <a-form
        :model="form"
        @submit.prevent="handleRegister"
        layout="vertical"
      >
        <a-form-item label="Username" required>
          <a-input
            v-model:value="form.username"
            placeholder="Choose a username"
            size="large"
          >
            <template #prefix>
              <User :size="16" class="text-gray-400" />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item label="Email" required>
          <a-input
            v-model:value="form.email"
            placeholder="Enter your email"
            type="email"
            size="large"
          >
            <template #prefix>
              <Mail :size="16" class="text-gray-400" />
            </template>
          </a-input>
        </a-form-item>

        <a-form-item label="Password" required>
          <a-input-password
            v-model:value="form.password"
            placeholder="Create a password"
            size="large"
          >
            <template #prefix>
              <Lock :size="16" class="text-gray-400" />
            </template>
          </a-input-password>
        </a-form-item>

        <a-form-item label="Confirm Password" required>
          <a-input-password
            v-model:value="form.confirmPassword"
            placeholder="Confirm your password"
            size="large"
          >
            <template #prefix>
              <Lock :size="16" class="text-gray-400" />
            </template>
          </a-input-password>
        </a-form-item>

        <a-button
          type="primary"
          html-type="submit"
          :loading="authStore.loading"
          block
          size="large"
          class="mb-4"
        >
          Sign Up
        </a-button>

        <div class="text-center">
          <span class="text-gray-600">Already have an account? </span>
          <router-link to="/login" class="text-blue-600 hover:text-blue-700">
            Sign in
          </router-link>
        </div>
      </a-form>

      <a-alert
        v-if="authStore.error"
        :message="authStore.error"
        type="error"
        show-icon
        closable
        @close="authStore.clearError"
        class="mt-4"
      />
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { Card, Form, Input, Button, Alert, message } from 'ant-design-vue';
import { User, Mail, Lock } from 'lucide-vue-next';
import { useAuthStore } from '../stores/auth';

const AForm = Form;
const AFormItem = Form.Item;
const AInput = Input;
const AInputPassword = Input.Password;
const AButton = Button;
const ACard = Card;
const AAlert = Alert;

const router = useRouter();
const authStore = useAuthStore();

const form = ref({
  username: '',
  email: '',
  password: '',
  confirmPassword: '',
});

const handleRegister = async () => {
  if (form.value.password !== form.value.confirmPassword) {
    message.error('Passwords do not match');
    return;
  }

  const success = await authStore.register(
    form.value.username,
    form.value.email,
    form.value.password
  );
  
  if (success) {
    message.success('Registration successful! Please login.');
    router.push('/login');
  }
};
</script>
