// slp/frontend-vue/src/features/question/components/MultipleChoice.vue
<!-- D:/SLP.Project/slp/frontend-vue/src/features/question/components/MultipleChoice.vue -->
<template>
  <a-form-item label="Options">
    <div v-for="(opt, index) in localOptions" :key="index" class="flex items-center mb-2">
      <a-checkbox
        :checked="isCorrect(opt)"
        @change="toggleCorrect(opt, $event.target.checked)"
        class="mr-2"
        :disabled="!opt.trim()"
        :data-testid="`mc-option-${index}-checkbox`"
      />
      <a-input
        v-model:value="localOptions[index]"
        placeholder="Option"
        style="margin-right: 8px; flex: 1;"
        :data-testid="`mc-option-${index}-input`"
      />
      <a-button @click="removeOption(index)" type="text" danger size="small" :data-testid="`mc-option-${index}-remove`">Remove</a-button>
    </div>
    <a-button @click="addOption" type="dashed" block data-testid="mc-add-option">Add Option</a-button>
  </a-form-item>
</template>

<script setup lang="ts">
import { ref, watch, nextTick } from 'vue';

const props = defineProps<{
  modelValue: string[];        // options
  correctAnswers: string[];     // selected correct options
}>();

const emit = defineEmits<{
  (e: 'update:modelValue', value: string[]): void;
  (e: 'update:correctAnswers', value: string[]): void;
}>();

// Local copy to allow direct editing
const localOptions = ref<string[]>([]);
const isInternalUpdate = ref(false); // flag to prevent emit loop when prop updates

// Initialize localOptions from props
const initFromProps = () => {
  isInternalUpdate.value = true;
  localOptions.value = props.modelValue.length ? [...props.modelValue] : ['', '', '', ''];
  nextTick(() => {
    isInternalUpdate.value = false;
  });
};

// Watch for external changes to modelValue
watch(() => props.modelValue, () => {
  initFromProps();
}, { deep: true, immediate: true });

// Watch localOptions and emit changes (skip internal updates)
watch(localOptions, (newVal) => {
  if (!isInternalUpdate.value) {
    emit('update:modelValue', newVal);
  }
}, { deep: true });

// Check if an option is currently marked correct
const isCorrect = (opt: string) => props.correctAnswers.includes(opt);

// Toggle correct status
const toggleCorrect = (opt: string, checked: boolean) => {
  let newCorrect = [...props.correctAnswers];
  if (checked) {
    if (!newCorrect.includes(opt)) newCorrect.push(opt);
  } else {
    newCorrect = newCorrect.filter(item => item !== opt);
  }
  emit('update:correctAnswers', newCorrect);
};

// Add a new empty option
const addOption = () => {
  localOptions.value.push('');
  // No need to emit manually; watcher will handle it
};

// Remove option at index, and remove it from correct answers if present
const removeOption = (index: number) => {
  const removed = localOptions.value[index];
  localOptions.value.splice(index, 1);
  // No need to emit manually; watcher will handle it

  // Remove from correct answers if that option was checked
  if (removed && props.correctAnswers.includes(removed)) {
    emit('update:correctAnswers', props.correctAnswers.filter(ans => ans !== removed));
  }
};
</script>

// slp/frontend-angular/src/features/question/components/multiple-choice.component.ts
// src/features/question/components/multiple-choice.component.ts
import { Component, Input, Output, EventEmitter, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { NzCheckboxModule } from "ng-zorro-antd/checkbox";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzFormModule } from "ng-zorro-antd/form";

@Component({
  selector: "app-multiple-choice",
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    NzCheckboxModule,
    NzInputModule,
    NzButtonModule,
    NzFormModule,
  ],
  template: `
    <nz-form-item>
      <nz-form-label>Options</nz-form-label>
      <nz-form-control>
        <div
          *ngFor="let opt of options; let i = index; trackBy: trackByIndex"
          class="flex items-center mb-2"
        >
          <label
            nz-checkbox
            [ngModel]="isCorrect(opt)"
            (ngModelChange)="toggleCorrect(opt, $event)"
            class="mr-2"
            [disabled]="!opt.trim()"
            [attr.data-testid]="'mc-option-' + i + '-checkbox'"
          >
          </label>
          <input
            nz-input
            [(ngModel)]="options[i]"
            placeholder="Option"
            class="flex-1 mr-2"
            (ngModelChange)="onOptionsChange()"
            [attr.data-testid]="'mc-option-' + i + '-input'"
          />
          <button
            nz-button
            nzType="text"
            nzDanger
            (click)="removeOption(i)"
            type="button"
            [attr.data-testid]="'mc-option-' + i + '-remove'"
          >
            Remove
          </button>
        </div>
        <button
          nz-button
          nzType="dashed"
          block
          (click)="addOption()"
          type="button"
          data-testid="mc-add-option"
        >
          Add Option
        </button>
      </nz-form-control>
    </nz-form-item>
  `,
  styles: [
    `
      .flex.items-center {
        gap: 8px;
      }
      .flex-1 {
        flex: 1;
      }
    `,
  ],
})
export class MultipleChoiceComponent implements OnInit {
  @Input() options: string[] = [];
  @Input() correctAnswers: string[] = [];
  @Output() optionsChange = new EventEmitter<string[]>();
  @Output() correctAnswersChange = new EventEmitter<string[]>();

  ngOnInit(): void {
    if (!this.options.length) this.options = ["", "", "", ""];
  }

  // Add trackBy function
  trackByIndex(index: number, item: string): number {
    return index;
  }

  isCorrect(opt: string): boolean {
    return this.correctAnswers.includes(opt);
  }

  toggleCorrect(opt: string, checked: boolean): void {
    let newCorrect = [...this.correctAnswers];
    if (checked) {
      if (!newCorrect.includes(opt)) newCorrect.push(opt);
    } else {
      newCorrect = newCorrect.filter((item) => item !== opt);
    }
    this.correctAnswersChange.emit(newCorrect);
  }

  addOption(): void {
    this.options.push("");
    this.optionsChange.emit(this.options);
  }

  removeOption(index: number): void {
    const removed = this.options[index];
    this.options.splice(index, 1);
    this.optionsChange.emit(this.options);
    if (removed && this.correctAnswers.includes(removed)) {
      this.correctAnswersChange.emit(
        this.correctAnswers.filter((ans) => ans !== removed),
      );
    }
  }

  onOptionsChange(): void {
    this.optionsChange.emit(this.options);
  }
}
