// slp/frontend-vue/src/features/quiz-attempt/components/MatchingQuestion.vue
<template>
  <div data-testid="matching-container">
    <div class="relative" ref="containerRef">
      <svg
        class="absolute inset-0 pointer-events-none"
        style="z-index: 1; overflow: visible;"
        :width="svgSize.w"
        :height="svgSize.h"
        data-testid="matching-svg"
      >
        <path
          v-for="(line, i) in lines"
          :key="`${line.leftId}-${line.rightId}`"
          :d="line.d"
          fill="none"
          :stroke="lineColors[i % lineColors.length]"
          stroke-width="2"
          stroke-linecap="round"
          opacity="0.65"
          :data-testid="`matching-line-${line.leftId}-${line.rightId}`"
        />
        <circle
          v-for="(line, i) in lines"
          :key="`dot-l-${line.leftId}`"
          :cx="line.x1" :cy="line.y1" r="3.5"
          :fill="lineColors[i % lineColors.length]"
          opacity="0.7"
        />
        <circle
          v-for="(line, i) in lines"
          :key="`dot-r-${line.rightId}`"
          :cx="line.x2" :cy="line.y2" r="3.5"
          :fill="lineColors[i % lineColors.length]"
          opacity="0.7"
        />
      </svg>

      <div class="grid grid-cols-2 gap-6">
        <!-- Left column -->
        <div class="flex flex-col gap-2" data-testid="matching-left-column">
          <div
            v-for="item in pairs"
            :key="'left-' + item.id"
            :ref="el => setRef(leftRefs, item.id, el)"
            @click="selectLeft(item.id)"
            :data-testid="`matching-left-${item.id}`"
            :data-matched="isMatched(item.id, 'left')"
            :data-selected="selectedLeft === item.id"
            :class="[
              'px-3 py-2.5 rounded-xl border-2 cursor-pointer select-none transition-all text-sm relative z-10',
              selectedLeft === item.id
                ? 'border-indigo-500 bg-indigo-50 text-indigo-700 shadow-md shadow-indigo-100'
                : isMatched(item.id, 'left')
                  ? 'border-green-500 bg-green-50 text-green-700'
                  : 'border-gray-200 bg-white text-gray-700 hover:border-indigo-300 hover:bg-indigo-50/40'
            ]"
          >
            <span class="flex items-center gap-2">
              <span
                v-if="isMatched(item.id, 'left')"
                class="inline-flex items-center justify-center w-4 h-4 rounded-full bg-green-500 text-white text-[10px] shrink-0"
                :data-testid="`matching-left-check-${item.id}`"
              >✓</span>
              <span :data-testid="`matching-left-text-${item.id}`">{{ item.left }}</span>
            </span>
          </div>
        </div>

        <!-- Right column -->
        <div class="flex flex-col gap-2" data-testid="matching-right-column">
          <div
            v-for="item in shuffledRight"
            :key="'right-' + item.id"
            :ref="el => setRef(rightRefs, item.id, el)"
            @click="selectRight(item.id)"
            :data-testid="`matching-right-${item.id}`"
            :data-matched="isMatched(item.id, 'right')"
            :class="[
              'px-3 py-2.5 rounded-xl border-2 cursor-pointer select-none transition-all text-sm relative z-10',
              isMatched(item.id, 'right')
                ? 'border-green-500 bg-green-50 text-green-700'
                : selectedLeft !== null
                  ? 'border-dashed border-indigo-300 bg-indigo-50/30 text-gray-700 hover:border-indigo-500 hover:bg-indigo-50'
                  : 'border-gray-200 bg-white text-gray-700 hover:border-gray-300'
            ]"
          >
            <span :data-testid="`matching-right-text-${item.id}`">{{ item.right }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="flex items-center justify-between mt-3">
      <span class="text-xs text-gray-400" data-testid="matching-progress">
        {{ modelValue.length }} / {{ pairs.length }} matched
      </span>
      <a-button
        size="small"
        danger
        ghost
        @click="reset"
        :disabled="modelValue.length === 0"
        data-testid="matching-reset"
      >
        Reset
      </a-button>
    </div>

    <div
      v-if="modelValue.length === pairs.length && pairs.length > 0"
      class="mt-2 text-center text-sm text-green-600 font-medium"
      data-testid="matching-complete"
    >
      ✓ All pairs matched!
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, nextTick } from 'vue';

interface Pair {
  id: number;
  left: string;
  right: string;
}

interface Line {
  leftId: number;
  rightId: number;
  x1: number; y1: number;
  x2: number; y2: number;
  d: string;
}

const props = withDefaults(defineProps<{
  pairs: Pair[];
  modelValue: Array<{ leftId: number; rightId: number }>;
}>(), {
  modelValue: () => [],
});

const emit = defineEmits(['update:modelValue']);

const lineColors = ['#6366f1', '#ec4899', '#f59e0b', '#10b981', '#3b82f6', '#8b5cf6'];

const selectedLeft = ref<number | null>(null);
const containerRef = ref<HTMLElement | null>(null);
const leftRefs = new Map<number, HTMLElement>();
const rightRefs = new Map<number, HTMLElement>();
const lines = ref<Line[]>([]);
const svgSize = ref({ w: 0, h: 0 });
const shuffledRight = ref<Pair[]>([]);

let ro: ResizeObserver | null = null;

onMounted(() => {
  shuffledRight.value = [...props.pairs].sort(() => Math.random() - 0.5);

  ro = new ResizeObserver(() => computeLines());
  if (containerRef.value) ro.observe(containerRef.value);

  nextTick(computeLines);
});

onBeforeUnmount(() => {
  ro?.disconnect();
});

watch(
  () => props.modelValue,
  () => nextTick(computeLines),
  { deep: true },
);

function setRef(map: Map<number, HTMLElement>, id: number, el: any) {
  if (el) map.set(id, el as HTMLElement);
  else map.delete(id);
}

function isMatched(id: number, side: 'left' | 'right') {
  return props.modelValue.some(m => side === 'left' ? m.leftId === id : m.rightId === id);
}

function selectLeft(id: number) {
  if (selectedLeft.value === id) { selectedLeft.value = null; return; }
  const filtered = props.modelValue.filter(m => m.leftId !== id);
  if (filtered.length !== props.modelValue.length) emit('update:modelValue', filtered);
  selectedLeft.value = id;
}

function selectRight(id: number) {
  if (selectedLeft.value === null) return;
  if (isMatched(id, 'right')) return;
  emit('update:modelValue', [...props.modelValue, { leftId: selectedLeft.value, rightId: id }]);
  selectedLeft.value = null;
}

function reset() {
  emit('update:modelValue', []);
  selectedLeft.value = null;
}

function computeLines() {
  const container = containerRef.value;
  if (!container) return;

  const cr = container.getBoundingClientRect();

  if (svgSize.value.w !== cr.width || svgSize.value.h !== cr.height) {
    svgSize.value = { w: cr.width, h: cr.height };
  }

  const newLines = props.modelValue.map(m => {
    const lEl = leftRefs.get(m.leftId);
    const rEl = rightRefs.get(m.rightId);
    if (!lEl || !rEl) return null;

    const lr = lEl.getBoundingClientRect();
    const rr = rEl.getBoundingClientRect();
    const x1 = lr.right - cr.left;
    const y1 = lr.top + lr.height / 2 - cr.top;
    const x2 = rr.left - cr.left;
    const y2 = rr.top + rr.height / 2 - cr.top;
    const cx = (x1 + x2) / 2;

    return {
      leftId: m.leftId, rightId: m.rightId,
      x1, y1, x2, y2,
      d: `M${x1},${y1} C${cx},${y1} ${cx},${y2} ${x2},${y2}`,
    };
  }).filter(Boolean) as Line[];

  lines.value = newLines;
}
</script>

// slp/frontend-angular/src/features/quiz-attempt/components/matching-question.component.ts
// src/features/quiz-attempt/components/matching-question.component.ts

import {
  Component,
  Input,
  Output,
  EventEmitter,
  ElementRef,
  ViewChild,
  AfterViewInit,
  OnDestroy,
  OnInit,
} from "@angular/core";
import { CommonModule } from "@angular/common";
import { NzButtonModule } from "ng-zorro-antd/button";

interface Pair {
  id: number;
  left: string;
  right: string;
}

interface Line {
  leftId: number;
  rightId: number;
  x1: number;
  y1: number;
  x2: number;
  y2: number;
  d: string;
}

@Component({
  selector: "app-matching-question",
  standalone: true,
  imports: [CommonModule, NzButtonModule],
  template: `
    <div #container class="relative" data-testid="matching-container">
      <svg
        class="absolute inset-0 pointer-events-none"
        style="z-index: 1; overflow: visible;"
        [attr.width]="svgWidth"
        [attr.height]="svgHeight"
        data-testid="matching-svg"
      >
        <path
          *ngFor="let line of lines; let i = index"
          [attr.d]="line.d"
          fill="none"
          [attr.stroke]="lineColors[i % lineColors.length]"
          stroke-width="2"
          stroke-linecap="round"
          opacity="0.65"
          [attr.data-testid]="
            'matching-line-' + line.leftId + '-' + line.rightId
          "
        />
        <circle
          *ngFor="let line of lines; let i = index"
          [attr.cx]="line.x1"
          [attr.cy]="line.y1"
          r="3.5"
          [attr.fill]="lineColors[i % lineColors.length]"
          opacity="0.7"
        />
        <circle
          *ngFor="let line of lines; let i = index"
          [attr.cx]="line.x2"
          [attr.cy]="line.y2"
          r="3.5"
          [attr.fill]="lineColors[i % lineColors.length]"
          opacity="0.7"
        />
      </svg>

      <div class="grid grid-cols-2 gap-6">
        <!-- Left column -->
        <div class="flex flex-col gap-2" data-testid="matching-left-column">
          <div
            *ngFor="let item of pairs"
            (click)="selectLeft(item.id)"
            class="px-3 py-2.5 rounded-xl border-2 cursor-pointer select-none transition-all text-sm relative z-10"
            [class.border-indigo-500]="selectedLeft === item.id"
            [class.bg-indigo-50]="selectedLeft === item.id"
            [class.text-indigo-700]="selectedLeft === item.id"
            [class.border-green-500]="isMatched(item.id, 'left')"
            [class.bg-green-50]="isMatched(item.id, 'left')"
            [class.text-green-700]="isMatched(item.id, 'left')"
            [class.border-gray-200]="
              !isMatched(item.id, 'left') && selectedLeft !== item.id
            "
            [class.bg-white]="
              !isMatched(item.id, 'left') && selectedLeft !== item.id
            "
            [class.hover:border-indigo-300]="!isMatched(item.id, 'left')"
            [attr.data-testid]="'matching-left-' + item.id"
            [attr.data-matched]="isMatched(item.id, 'left')"
            [attr.data-selected]="selectedLeft === item.id"
          >
            <span class="flex items-center gap-2">
              <span
                *ngIf="isMatched(item.id, 'left')"
                class="inline-flex items-center justify-center w-4 h-4 rounded-full bg-green-500 text-white text-[10px] shrink-0"
                [attr.data-testid]="'matching-left-check-' + item.id"
              >
                ✓
              </span>
              <span [attr.data-testid]="'matching-left-text-' + item.id">
                {{ item.left }}
              </span>
            </span>
          </div>
        </div>

        <!-- Right column -->
        <div class="flex flex-col gap-2" data-testid="matching-right-column">
          <div
            *ngFor="let item of shuffledRight"
            (click)="selectRight(item.id)"
            class="px-3 py-2.5 rounded-xl border-2 cursor-pointer select-none transition-all text-sm relative z-10"
            [class.border-green-500]="isMatched(item.id, 'right')"
            [class.bg-green-50]="isMatched(item.id, 'right')"
            [class.text-green-700]="isMatched(item.id, 'right')"
            [class.border-dashed]="
              !isMatched(item.id, 'right') && selectedLeft !== null
            "
            [class.border-indigo-300]="
              !isMatched(item.id, 'right') && selectedLeft !== null
            "
            [class.bg-indigo-50/30]="
              !isMatched(item.id, 'right') && selectedLeft !== null
            "
            [class.border-gray-200]="
              !isMatched(item.id, 'right') && selectedLeft === null
            "
            [class.bg-white]="
              !isMatched(item.id, 'right') && selectedLeft === null
            "
            [class.hover:border-indigo-500]="
              !isMatched(item.id, 'right') && selectedLeft !== null
            "
            [attr.data-testid]="'matching-right-' + item.id"
            [attr.data-matched]="isMatched(item.id, 'right')"
          >
            <span [attr.data-testid]="'matching-right-text-' + item.id">
              {{ item.right }}
            </span>
          </div>
        </div>
      </div>

      <div class="flex items-center justify-between mt-3">
        <span class="text-xs text-gray-400" data-testid="matching-progress">
          {{ value.length }} / {{ pairs.length }} matched
        </span>
        <button
          nz-button
          nzSize="small"
          nzDanger
          nzGhost
          (click)="reset()"
          [disabled]="value.length === 0"
          data-testid="matching-reset"
        >
          Reset
        </button>
      </div>

      <div
        *ngIf="value.length === pairs.length && pairs.length > 0"
        class="mt-2 text-center text-sm text-green-600 font-medium"
        data-testid="matching-complete"
      >
        ✓ All pairs matched!
      </div>
    </div>
  `,
})
export class MatchingQuestionComponent
  implements AfterViewInit, OnDestroy, OnInit
{
  @Input() pairs: Pair[] = [];
  @Input() value: Array<{ leftId: number; rightId: number }> = [];
  @Output() valueChange = new EventEmitter<
    Array<{ leftId: number; rightId: number }>
  >();

  @ViewChild("container") container!: ElementRef<HTMLElement>;

  selectedLeft: number | null = null;
  shuffledRight: Pair[] = [];
  lines: Line[] = [];
  svgWidth = 0;
  svgHeight = 0;
  lineColors = [
    "#6366f1",
    "#ec4899",
    "#f59e0b",
    "#10b981",
    "#3b82f6",
    "#8b5cf6",
  ];

  private resizeObserver?: ResizeObserver;
  private leftRefs = new Map<number, HTMLElement>();
  private rightRefs = new Map<number, HTMLElement>();

  ngOnInit(): void {
    // Shuffle right column
    this.shuffledRight = [...this.pairs].sort(() => Math.random() - 0.5);
  }

  ngAfterViewInit(): void {
    this.resizeObserver = new ResizeObserver(() => this.computeLines());
    this.resizeObserver.observe(this.container.nativeElement);
    setTimeout(() => this.computeLines(), 0);
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
  }

  isMatched(id: number, side: "left" | "right"): boolean {
    return this.value.some((m) =>
      side === "left" ? m.leftId === id : m.rightId === id,
    );
  }

  selectLeft(id: number): void {
    if (this.isMatched(id, "left")) return;
    if (this.selectedLeft === id) {
      this.selectedLeft = null;
      return;
    }
    this.selectedLeft = id;
  }

  selectRight(id: number): void {
    if (this.selectedLeft === null) return;
    if (this.isMatched(id, "right")) return;
    const newMatches = [
      ...this.value,
      { leftId: this.selectedLeft, rightId: id },
    ];
    this.valueChange.emit(newMatches);
    this.selectedLeft = null;
  }

  reset(): void {
    this.valueChange.emit([]);
    this.selectedLeft = null;
  }

  private computeLines(): void {
    const containerRect = this.container.nativeElement.getBoundingClientRect();
    this.svgWidth = containerRect.width;
    this.svgHeight = containerRect.height;

    const newLines: Line[] = [];
    for (const match of this.value) {
      const leftEl = this.leftRefs.get(match.leftId);
      const rightEl = this.rightRefs.get(match.rightId);
      if (!leftEl || !rightEl) continue;

      const leftRect = leftEl.getBoundingClientRect();
      const rightRect = rightEl.getBoundingClientRect();

      const x1 = leftRect.right - containerRect.left;
      const y1 = leftRect.top + leftRect.height / 2 - containerRect.top;
      const x2 = rightRect.left - containerRect.left;
      const y2 = rightRect.top + rightRect.height / 2 - containerRect.top;
      const cx = (x1 + x2) / 2;

      newLines.push({
        leftId: match.leftId,
        rightId: match.rightId,
        x1,
        y1,
        x2,
        y2,
        d: `M${x1},${y1} C${cx},${y1} ${cx},${y2} ${x2},${y2}`,
      });
    }
    this.lines = newLines;
  }

  // Helper to set element references
  setLeftRef(id: number, el: HTMLElement) {
    if (el) this.leftRefs.set(id, el);
    else this.leftRefs.delete(id);
  }
  setRightRef(id: number, el: HTMLElement) {
    if (el) this.rightRefs.set(id, el);
    else this.rightRefs.delete(id);
  }
}
