// slp/frontend-vue/src/features/comment/components/CommentsSection.vue
<template>
  <a-card
    title="Comments"
    class="shadow-sm mt-4"
    data-testid="comments-section"
  >
    <div v-if="store.loading" class="text-center py-4">
      <a-spin size="small" data-testid="comments-loading" />
    </div>
    <div v-else>
      <!-- New top‑level comment form -->
      <div v-if="isAuthenticated" class="mb-4">
        <a-textarea
          v-model:value="newCommentContent"
          placeholder="Write a comment..."
          :rows="2"
          data-testid="new-comment-input"
        />
        <a-button
          type="primary"
          class="mt-2"
          @click="handleAddComment"
          :loading="store.loading"
          data-testid="submit-comment-button"
        >
          Add Comment
        </a-button>
      </div>
      <div v-else class="text-gray-500 mb-4">
        <a href="/login" data-testid="login-to-comment">Log in</a> to comment.
      </div>

      <!-- Comments list -->
      <div
        v-if="store.comments.length === 0"
        class="text-gray-400 text-sm py-2"
        data-testid="no-comments-message"
      >
        No comments yet.
      </div>
      <div v-else class="space-y-4">
        <CommentItem
          v-for="comment in store.comments"
          :key="comment.id"
          :comment="comment"
          :target-type="targetType"
          :target-id="targetId"
          :is-authenticated="isAuthenticated"
          :current-user-id="currentUserId"
          :is-admin="isAdmin"
          @reply="openReplyForm"
          @edit="() => {}"
          @delete="handleDeleteComment"
          @report="openReportModal"
        />
      </div>
    </div>

    <!-- Reply modal with custom footer buttons -->
    <a-modal
      v-model:visible="replyModalVisible"
      title="Reply to comment"
      :confirm-loading="store.loading"
      data-testid="reply-modal"
    >
      <a-textarea
        v-model:value="replyContent"
        :rows="3"
        placeholder="Write your reply..."
        data-testid="reply-input"
      />
      <template #footer>
        <a-button
          key="cancel"
          @click="replyModalVisible = false"
          data-testid="reply-modal-cancel"
        >
          Cancel
        </a-button>
        <a-button
          key="submit"
          type="primary"
          :loading="store.loading"
          @click="handleReplySubmit"
          data-testid="reply-modal-ok"
        >
          Reply
        </a-button>
      </template>
    </a-modal>

    <ReportModal
      v-model:visible="reportModalVisible"
      :target-type="'comment'"
      :target-id="reportingCommentId!"
      @reported="reportModalVisible = false"
    />
  </a-card>
</template>

<script setup lang="ts">
import { ref, computed } from "vue";
import { message } from "ant-design-vue";
import { useCommentStore } from "../stores/commentStore";
import { useAuthStore } from "@/features/auth/stores/authStore";
import CommentItem from "./CommentItem.vue";
import ReportModal from "@/features/report/components/ReportModal.vue";

const props = defineProps<{
  targetType: string;
  targetId: number;
}>();

const store = useCommentStore();
const authStore = useAuthStore();

const isAuthenticated = computed(() => authStore.isAuthenticated);
const currentUserId = computed(() => authStore.user?.id);
const isAdmin = computed(() => authStore.isAdmin);

const newCommentContent = ref("");
const replyModalVisible = ref(false);
const replyContent = ref("");
const replyingTo = ref<number | null>(null);
const reportModalVisible = ref(false);
const reportingCommentId = ref<number | null>(null);

const openReportModal = (commentId: number) => {
  reportingCommentId.value = commentId;
  reportModalVisible.value = true;
};

const fetchComments = async () => {
  await store.fetchComments(props.targetType, props.targetId);
};

const handleAddComment = async () => {
  if (!newCommentContent.value.trim()) {
    message.warning("Comment cannot be empty");
    return;
  }
  try {
    await store.createComment({
      targetType: props.targetType,
      targetId: props.targetId,
      content: newCommentContent.value,
    });
    newCommentContent.value = "";
    message.success("Comment added");
  } catch {
    // error already in store
  }
};

const openReplyForm = (commentId: number) => {
  replyingTo.value = commentId;
  replyContent.value = "";
  replyModalVisible.value = true;
};

const handleReplySubmit = async () => {
  if (!replyContent.value.trim()) {
    message.warning("Reply cannot be empty");
    return;
  }
  try {
    await store.createComment({
      parentId: replyingTo.value!,
      targetType: props.targetType,
      targetId: props.targetId,
      content: replyContent.value,
    });
    replyModalVisible.value = false;
    message.success("Reply added");
  } catch {
    // handled
  }
};

const handleDeleteComment = async (commentId: number) => {
  const success = await store.deleteComment(
    commentId,
    props.targetType,
    props.targetId,
  );
  if (success) {
    message.success("Comment deleted");
  } else {
    message.error("Failed to delete comment");
  }
};

// Initial fetch
fetchComments();
</script>

// slp/frontend-angular/src/features/comment/components/comments-section/comments-section.component.ts
// src/features/comment/components/comments-section/comments-section.component.ts
import { Component, Input, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NzCardModule } from 'ng-zorro-antd/card';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzMessageService } from 'ng-zorro-antd/message';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { RouterLink } from '@angular/router';
import { CommentService } from '../../services/comment.service';
import { AuthService } from '../../../../features/auth/auth.service';
import { CommentItemComponent } from '../comment-item/comment-item.component';
import { ReportModalComponent } from '../features/report/components/report-modal.component'; // adjust path

@Component({
  selector: 'app-comments-section',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    NzCardModule,
    NzSpinModule,
    NzInputModule,
    NzButtonModule,
    NzModalModule,
    TranslateModule,
    RouterLink,
    CommentItemComponent,
    ReportModalComponent
  ],
  template: `
    <nz-card nzTitle="{{ 'comment.title' | translate }}" class="shadow-sm mt-4" data-testid="comments-section">
      <div *ngIf="loading$ | async" class="text-center py-4">
        <nz-spin nzSize="small" data-testid="comments-loading" />
      </div>
      <div *ngIf="!(loading$ | async)">
        <!-- New top‑level comment form -->
        <div *ngIf="isAuthenticated" class="mb-4">
          <textarea
            nz-input
            rows="2"
            placeholder="{{ 'comment.writeComment' | translate }}"
            [(ngModel)]="newCommentContent"
            data-testid="new-comment-input"
          ></textarea>
          <button
            nz-button
            nzType="primary"
            class="mt-2"
            (click)="handleAddComment()"
            [nzLoading]="loading$ | async"
            data-testid="submit-comment-button"
          >
            {{ 'comment.addComment' | translate }}
          </button>
        </div>
        <div *ngIf="!isAuthenticated" class="text-gray-500 mb-4">
          <a routerLink="/login" data-testid="login-to-comment">{{ 'comment.loginToComment' | translate }}</a>
        </div>

        <!-- Comments list -->
        <div *ngIf="(comments$ | async)?.length === 0" class="text-gray-400 text-sm py-2" data-testid="no-comments-message">
          {{ 'comment.noComments' | translate }}
        </div>
        <div *ngIf="(comments$ | async)?.length" class="space-y-4">
          <app-comment-item
            *ngFor="let comment of comments$ | async"
            [comment]="comment"
            [targetType]="targetType"
            [targetId]="targetId"
            (reply)="openReplyForm($event)"
            (edit)="() => {}"
            (delete)="handleDeleteComment($event)"
            (report)="openReportModal($event)"
          ></app-comment-item>
        </div>
      </div>

      <!-- Reply modal -->
      <nz-modal
        [(nzVisible)]="replyModalVisible"
        nzTitle="{{ 'comment.reply' | translate }}"
        [nzConfirmLoading]="loading$ | async"
        (nzOnOk)="handleReplySubmit()"
        [nzOkText]="'comment.reply' | translate"
        [nzCancelText]="'common.cancel' | translate"
        data-testid="reply-modal"
      >
        <textarea
          nz-input
          rows="3"
          placeholder="{{ 'comment.writeReply' | translate }}"
          [(ngModel)]="replyContent"
          data-testid="reply-input"
        ></textarea>
      </nz-modal>

      <!-- Report modal -->
      <app-report-modal
        [(visible)]="reportModalVisible"
        [targetType]="'comment'"
        [targetId]="reportingCommentId!"
        (reported)="onReported()"
      ></app-report-modal>
    </nz-card>
  `,
  styles: []
})
export class CommentsSectionComponent implements OnInit, OnDestroy {
  @Input() targetType!: string;
  @Input() targetId!: number;

  newCommentContent = '';
  replyModalVisible = false;
  replyContent = '';
  replyingTo: number | null = null;
  reportModalVisible = false;
  reportingCommentId: number | null = null;

  comments$ = this.commentService.comments$;
  loading$ = this.commentService.loading$;

  isAuthenticated = false;
  currentUserId: number | null = null;
  isAdmin = false;

  constructor(
    private commentService: CommentService,
    private authService: AuthService,
    private message: NzMessageService,
    private translate: TranslateService
  ) {}

  ngOnInit(): void {
    this.authService.user$.subscribe(user => {
      this.isAuthenticated = !!user;
      this.currentUserId = user?.id || null;
      this.isAdmin = user?.role === 'admin';
    });
    this.fetchComments();
  }

  ngOnDestroy(): void {
    // No need to unsubscribe because we use async pipe
  }

  fetchComments(): void {
    this.commentService.fetchComments(this.targetType, this.targetId);
  }

  async handleAddComment(): Promise<void> {
    if (!this.newCommentContent.trim()) {
      this.message.warning(this.translate.instant('comment.contentRequired'));
      return;
    }
    try {
      await this.commentService.createComment({
        targetType: this.targetType,
        targetId: this.targetId,
        content: this.newCommentContent
      }).toPromise();
      this.newCommentContent = '';
      this.message.success(this.translate.instant('comment.addSuccess'));
    } catch {
      // error handled in service
    }
  }

  openReplyForm(commentId: number): void {
    this.replyingTo = commentId;
    this.replyContent = '';
    this.replyModalVisible = true;
  }

  async handleReplySubmit(): Promise<void> {
    if (!this.replyContent.trim()) {
      this.message.warning(this.translate.instant('comment.contentRequired'));
      return;
    }
    try {
      await this.commentService.createComment({
        parentId: this.replyingTo!,
        targetType: this.targetType,
        targetId: this.targetId,
        content: this.replyContent
      }).toPromise();
      this.replyModalVisible = false;
      this.message.success(this.translate.instant('comment.replySuccess'));
    } catch {
      // handled
    }
  }

  async handleDeleteComment(commentId: number): Promise<void> {
    try {
      await this.commentService.deleteComment(commentId).toPromise();
      this.message.success(this.translate.instant('comment.deleteSuccess'));
    } catch {
      this.message.error(this.translate.instant('comment.deleteError'));
    }
  }

  openReportModal(commentId: number): void {
    this.reportingCommentId = commentId;
    this.reportModalVisible = true;
  }

  onReported(): void {
    this.reportModalVisible = false;
    this.reportingCommentId = null;
  }
}
