// slp/frontend-angular/src/features/quiz/components/question-picker-modal.component.ts
// src/features/quiz/components/question-picker-modal.component.ts

import { Component, Input, Output, EventEmitter, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Subject, debounceTime, distinctUntilChanged, takeUntil } from 'rxjs';
import { NzModalModule } from 'ng-zorro-antd/modal';
import { NzListModule } from 'ng-zorro-antd/list';
import { NzTagModule } from 'ng-zorro-antd/tag';
import { NzInputModule } from 'ng-zorro-antd/input';
import { NzSelectModule } from 'ng-zorro-antd/select';
import { NzPaginationModule } from 'ng-zorro-antd/pagination';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { NzButtonModule } from 'ng-zorro-antd/button';
import { TranslateModule } from '@ngx-translate/core';
import { QuestionService } from '../../question/question.service';
import { QuestionListDto } from '../../question/question.model';

@Component({
  selector: 'app-question-picker-modal',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    NzModalModule,
    NzListModule,
    NzTagModule,
    NzInputModule,
    NzSelectModule,
    NzPaginationModule,
    NzSpinModule,
    NzButtonModule,
    TranslateModule,
  ],
  template: `
    <nz-modal
      [(nzVisible)]="visible"
      nzTitle="{{ 'quiz.findQuestion' | translate }}"
      [nzFooter]="null"
      [nzWidth]="800"
      (nzOnCancel)="handleCancel()"
      data-testid="question-picker-modal"
    >
      <div class="space-y-3">
        <div class="flex flex-col gap-2">
          <input nz-input [(ngModel)]="search" (ngModelChange)="onSearchChange()" placeholder="{{ 'quiz.searchQuestions' | translate }}" data-testid="picker-search" />
          <div class="flex gap-2">
            <nz-select [(ngModel)]="typeFilter" nzPlaceHolder="{{ 'quiz.filterByType' | translate }}" allowClear style="width: 140px" (ngModelChange)="onFilterChange()" data-testid="picker-type-filter">
              <nz-option nzValue="multiple_choice" nzLabel="Multiple Choice"></nz-option>
              <nz-option nzValue="true_false" nzLabel="True/False"></nz-option>
              <nz-option nzValue="fill_blank" nzLabel="Fill in the Blank"></nz-option>
              <nz-option nzValue="ordering" nzLabel="Ordering"></nz-option>
              <nz-option nzValue="matching" nzLabel="Matching"></nz-option>
            </nz-select>
            <input nz-input [(ngModel)]="tagFilter" (ngModelChange)="onFilterChange()" placeholder="{{ 'quiz.filterByTag' | translate }}" class="flex-1" data-testid="picker-tag-filter" />
          </div>
        </div>

        <nz-spin [nzSpinning]="loading">
          <nz-list [nzDataSource]="questions" nzItemLayout="vertical" data-testid="picker-questions-list">
            <nz-list-item *ngFor="let q of questions" [attr.data-testid]="'picker-question-' + q.id">
              <nz-list-item-meta>
                <nz-list-item-meta-title>
                  <div class="flex items-center justify-between gap-2">
                    <span class="font-medium">{{ q.content }}</span>
                    <nz-tag>{{ formatType(q.type) }}</nz-tag>
                  </div>
                </nz-list-item-meta-title>
                <nz-list-item-meta-description>
                  <div class="text-sm">
                    <p class="text-gray-500">{{ getDescription(q) || ('quiz.noDescription' | translate) }}</p>
                    <div class="flex flex-wrap gap-1 mt-1">
                      <nz-tag *ngFor="let tag of q.tags" size="small">{{ tag }}</nz-tag>
                    </div>
                  </div>
                </nz-list-item-meta-description>
              </nz-list-item-meta>
              <ul nz-list-item-actions>
                <nz-list-item-action>
                  <button nz-button nzType="primary" size="small" (click)="select.emit(q)" data-testid="picker-select-button">
                    {{ 'quiz.select' | translate }}
                  </button>
                </nz-list-item-action>
              </ul>
            </nz-list-item>
          </nz-list>
        </nz-spin>

        <div *ngIf="total > pageSize" class="flex justify-center mt-4">
          <nz-pagination
            [nzPageIndex]="currentPage"
            [nzTotal]="total"
            [nzPageSize]="pageSize"
            [nzShowSizeChanger]="false"
            (nzPageIndexChange)="onPageChange($event)"
            data-testid="picker-pagination"
          ></nz-pagination>
        </div>

        <div *ngIf="!loading && questions.length === 0" class="text-center py-12 text-gray-400">
          <p class="text-base">{{ 'quiz.noQuestionsFound' | translate }}</p>
        </div>
      </div>
    </nz-modal>
  `,
})
export class QuestionPickerModalComponent implements OnInit, OnDestroy {
  @Input() visible = false;
  @Output() visibleChange = new EventEmitter<boolean>();
  @Output() select = new EventEmitter<QuestionListDto>();

  search = '';
  typeFilter?: string;
  tagFilter = '';
  currentPage = 1;
  pageSize = 10;
  questions: QuestionListDto[] = [];
  loading = false;
  total = 0;

  private searchDebouncer = new Subject<string>();
  private destroy$ = new Subject<void>();

  constructor(private questionService: QuestionService) {}

  ngOnInit(): void {
    this.searchDebouncer.pipe(debounceTime(500), distinctUntilChanged(), takeUntil(this.destroy$)).subscribe(() => {
      this.currentPage = 1;
      this.fetchQuestions();
    });
  }

  ngOnDestroy(): void {
    this.destroy$.next();
    this.destroy$.complete();
  }

  onSearchChange(): void {
    this.searchDebouncer.next(this.search);
  }

  onFilterChange(): void {
    this.currentPage = 1;
    this.fetchQuestions();
  }

  onPageChange(page: number): void {
    this.currentPage = page;
    this.fetchQuestions();
  }

  fetchQuestions(): void {
    this.loading = true;
    const params: any = {
      search: this.search || undefined,
      type: this.typeFilter || undefined,
      tags: this.tagFilter || undefined,
    };
    this.questionService.fetchQuestions(params, this.currentPage, this.pageSize);
    // Wait for the service to update its observables
    this.questionService.questions$.pipe(takeUntil(this.destroy$)).subscribe(questions => {
      this.questions = questions;
    });
    this.questionService.total$.pipe(takeUntil(this.destroy$)).subscribe(total => {
      this.total = total;
    });
    this.loading = false;
  }

  formatType(type: string): string {
    if (!type) return 'Unknown';
    return type.split(/[_\-]/).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
  }

  getDescription(item: QuestionListDto): string {
    if (!item.metadataJson) return '';
    try {
      const meta = JSON.parse(item.metadataJson);
      return meta.description || '';
    } catch {
      return '';
    }
  }

  handleCancel(): void {
    this.visible = false;
    this.visibleChange.emit(false);
  }
}

// slp/frontend-vue/src/features/quiz/components/QuestionPickerModal.vue
<template>
  <a-modal
    :visible="visible"
    title="Find Question"
    :footer="null"
    @cancel="handleCancel"
    width="90%"
    :mask-closable="false"
    wrap-class-name="full-width-modal"
    data-testid="question-picker-modal"
  >
    <div class="space-y-3">
      <!-- Filters -->
      <div class="flex flex-col gap-2">
        <a-input-search
          v-model:value="search"
          placeholder="Search questions..."
          enter-button
          @search="handleSearch"
          data-testid="picker-search"
        />
        <div class="flex gap-2">
          <a-select
            v-model:value="typeFilter"
            placeholder="All Types"
            style="width: 140px"
            allow-clear
            @change="handleFilterChange"
            data-testid="picker-type-filter"
          >
            <a-select-option value="multiple_choice">Multiple Choice</a-select-option>
            <a-select-option value="true_false">True/False</a-select-option>
            <a-select-option value="fill_blank">Fill Blank</a-select-option>
            <a-select-option value="ordering">Ordering</a-select-option>
            <a-select-option value="matching">Matching</a-select-option>
          </a-select>
          <a-input
            v-model:value="tagFilter"
            placeholder="Filter by tag"
            style="flex: 1"
            @pressEnter="handleFilterChange"
            data-testid="picker-tag-filter"
          />
        </div>
      </div>

      <!-- Questions list -->
      <a-list
        :loading="loading"
        :data-source="questions"
        item-layout="vertical"
        data-testid="picker-questions-list"
      >
        <template #renderItem="{ item }">
          <a-list-item :data-testid="`picker-question-${item.id}`">
            <a-list-item-meta>
              <template #title>
                <div class="flex items-center justify-between gap-2">
                  <span class="font-medium">{{ item.content }}</span>
                  <a-tag>{{ formatType(item.type) }}</a-tag>
                </div>
              </template>
              <template #description>
                <div class="text-sm">
                  <p class="text-gray-500">{{ getDescription(item) || 'No description' }}</p>
                  <div class="flex flex-wrap gap-1 mt-1">
                    <a-tag v-for="tag in item.tags" :key="tag" size="small">{{ tag }}</a-tag>
                  </div>
                </div>
              </template>
            </a-list-item-meta>
            <template #actions>
              <a-button type="primary" size="small" @click="handleSelect(item)" data-testid="picker-select-button">
                Select
              </a-button>
            </template>
          </a-list-item>
        </template>
      </a-list>

      <!-- Pagination -->
      <div v-if="total > pageSize" class="flex justify-center mt-4">
        <a-pagination
          v-model:current="currentPage"
          :total="total"
          :page-size="pageSize"
          :show-size-changer="false"
          simple
          @change="handlePageChange"
          data-testid="picker-pagination"
        />
      </div>

      <!-- Empty state -->
      <div v-if="!loading && questions.length === 0" class="text-center py-12 text-gray-400">
        <p class="text-base">No questions found.</p>
      </div>
    </div>
  </a-modal>
</template>

<script setup lang="ts">
import { ref, watch } from 'vue';
import { useQuestionStore } from '@/features/question/stores/questionStore';

const props = defineProps<{
  visible: boolean;
}>();

const emit = defineEmits<{
  (e: 'update:visible', value: boolean): void;
  (e: 'select', question: any): void;
}>();

const questionStore = useQuestionStore();

const search = ref('');
const typeFilter = ref<string | undefined>(undefined);
const tagFilter = ref('');
const currentPage = ref(1);
const pageSize = 10;

const questions = ref<any[]>([]);
const loading = ref(false);
const total = ref(0);

const formatType = (type: string) => {
  if (!type) return 'Unknown';
  return type.split(/[_\-]/).map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase()).join(' ');
};

const getDescription = (item: any) => {
  if (!item.metadataJson) return '';
  try {
    const metadata = JSON.parse(item.metadataJson);
    return metadata.description || '';
  } catch {
    return '';
  }
};

const fetchQuestions = async () => {
  loading.value = true;
  try {
    const params: any = {
      search: search.value || undefined,
      type: typeFilter.value || undefined,
      tag: tagFilter.value || undefined,
    };
    await questionStore.fetchQuestions(params, currentPage.value, pageSize);
    questions.value = [...questionStore.questions];
    total.value = questionStore.total;
  } catch (err) {
    console.error('Failed to fetch questions', err);
  } finally {
    loading.value = false;
  }
};

const handleSearch = () => {
  currentPage.value = 1;
  fetchQuestions();
};

const handleFilterChange = () => {
  currentPage.value = 1;
  fetchQuestions();
};

const handlePageChange = (page: number) => {
  currentPage.value = page;
  fetchQuestions();
};

const handleSelect = (question: any) => {
  emit('select', question);
  emit('update:visible', false);
};

const handleCancel = () => {
  emit('update:visible', false);
};

watch(() => props.visible, (newVal) => {
  if (newVal) {
    fetchQuestions();
  } else {
    search.value = '';
    typeFilter.value = undefined;
    tagFilter.value = '';
    currentPage.value = 1;
    questions.value = [];
  }
});
</script>

<style scoped>
.full-width-modal .ant-modal {
  max-width: 100%;
  margin: 0;
  top: 0;
  height: 100%;
}
.full-width-modal .ant-modal-content {
  height: 100%;
  border-radius: 0;
  overflow-y: auto;
}
</style>
