// slp/frontend-vue/src/features/source/components/ExplanationPanel.vue
<template>
  <div
    class="fixed top-0 right-0 h-screen w-[320px] bg-[#faf9f6] border-l border-[#e8e4dc] shadow-[-4px_0_24px_rgba(0,0,0,0.06)] z-[200] flex flex-col transition-transform duration-[280ms] ease-[cubic-bezier(0.4,0,0.2,1)]"
    :class="isOpen ? 'translate-x-0' : 'translate-x-full'"
    data-testid="explanation-panel"
  >
    <!-- Toggle handle -->
    <button
      class="absolute left-[-32px] top-1/2 -translate-y-1/2 w-8 h-12 bg-[#faf9f6] border border-[#e8e4dc] border-r-0 rounded-l-[8px] cursor-pointer flex items-center justify-center text-gray-400 transition-colors hover:text-gray-700"
      @click="isOpen ? $emit('close') : $emit('open')"
      data-testid="explanation-panel-toggle-btn"
    >
      <ChevronRight :size="16" />
    </button>

    <!-- Scrollable inner -->
    <div class="flex-1 overflow-y-auto flex flex-col">
      <!-- Header -->
      <div
        class="flex items-center justify-between px-5 pt-5 pb-4 border-b border-[#e8e4dc]"
      >
        <div class="flex items-center gap-2">
          <Sparkles :size="16" class="text-[#7c6af5]" />
          <h3
            class="text-sm font-semibold text-[#1a1a2e] m-0 tracking-[-0.01em]"
          >
            Explanations
          </h3>
        </div>
        <button
          class="bg-transparent border-0 text-gray-400 cursor-pointer p-1 rounded transition-all hover:text-gray-700 hover:bg-gray-100"
          @click="$emit('close')"
          data-testid="explanation-panel-close-btn"
        >
          <X :size="16" />
        </button>
      </div>

      <!-- Selected text preview -->
      <div
        v-if="pendingText"
        class="m-4 p-[14px] bg-white border border-[#e8e4dc] rounded-[10px]"
        data-testid="explanation-panel-preview"
      >
        <p
          class="text-[10px] font-semibold uppercase tracking-[0.08em] text-gray-400 mt-0 mb-2"
        >
          Selected text
        </p>
        <blockquote
          class="text-[13px] text-gray-700 italic border-l-[3px] border-[#7c6af5] pl-[10px] mt-0 mb-3 leading-[1.5]"
          data-testid="explanation-panel-preview-text"
        >
          {{ truncate(pendingText, 120) }}
        </blockquote>
        <div class="flex gap-2">
          <button
            class="flex items-center gap-[5px] px-3 py-1.5 rounded-[7px] text-xs font-medium cursor-pointer border-0 bg-[#7c6af5] text-white font-[inherit] transition-all hover:bg-[#6c5ce7]"
            @click="$emit('request-explain', pendingText)"
            data-testid="explanation-panel-explain-btn"
          >
            <Sparkles :size="13" />
            Explain with AI
          </button>
          <button
            class="flex items-center gap-[5px] px-3 py-1.5 rounded-[7px] text-xs font-medium cursor-pointer border border-[#e8e4dc] bg-white text-gray-700 font-[inherit] transition-all hover:bg-gray-50 hover:border-gray-300"
            @click="$emit('clear-pending')"
            data-testid="explanation-panel-clear-btn"
          >
            <X :size="13" />
            Clear
          </button>
        </div>
      </div>

      <!-- Loading -->
      <div
        v-if="loading"
        class="flex flex-col items-center justify-center gap-3 px-5 py-10 text-gray-400 text-[13px] text-center flex-1"
        data-testid="explanation-panel-loading"
      >
        <a-spin size="small" />
        <span>Loading...</span>
      </div>

      <!-- Empty -->
      <div
        v-else-if="explanations.length === 0 && !pendingText"
        class="flex flex-col items-center justify-center gap-3 px-5 py-10 text-gray-400 text-[13px] text-center flex-1"
        data-testid="explanation-panel-empty"
      >
        <BookOpen :size="32" class="text-gray-300" />
        <p>Select text in the article to get AI explanations.</p>
      </div>

      <!-- List -->
      <div
        v-else
        class="py-3 px-4 flex flex-col gap-3"
        data-testid="explanation-panel-list"
      >
        <div
          v-for="exp in explanations"
          :key="exp.id"
          class="bg-white border border-[#e8e4dc] rounded-[10px] p-[14px] transition-shadow hover:shadow-[0_2px_12px_rgba(0,0,0,0.06)]"
          :data-testid="`explanation-panel-card-${exp.id}`"
        >
          <!-- Quote -->
          <div
            class="text-xs text-gray-500 italic mb-2 leading-[1.4]"
            :data-testid="`explanation-panel-card-quote-${exp.id}`"
          >
            <span
              class="text-lg text-[#7c6af5] leading-none align-[-4px] mr-0.5"
              >"</span
            >
            {{ truncate(exp.textRange?.text ?? "", 80) }}
          </div>

          <!-- Content -->
          <div
            v-if="exp.content"
            class="text-[13px] text-gray-700 leading-[1.6]"
            :data-testid="`explanation-panel-card-content-${exp.id}`"
          >
            {{ exp.content }}
          </div>

          <!-- Pending -->
          <div
            v-else
            class="flex items-center gap-2 text-xs text-gray-400"
            :data-testid="`explanation-panel-card-pending-${exp.id}`"
          >
            <a-spin size="small" />
            <span>Generating explanation…</span>
          </div>

          <!-- Meta -->
          <div
            class="text-[11px] text-[#c4bfb5] mt-2"
            :data-testid="`explanation-panel-card-meta-${exp.id}`"
          >
            {{ formatDate(exp.createdAt) }}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { Sparkles, X, ChevronRight, BookOpen } from "lucide-vue-next";

/** Matches the backend ExplanationDto exactly. */
export interface ExplanationItem {
  id: number;
  userId?: number;
  sourceId?: number;
  textRange?: { text?: string; [key: string]: any } | null;
  content: string;
  authorType?: string;
  editable?: boolean;
  createdAt: string;
  updatedAt?: string | null;
}

defineProps<{
  isOpen: boolean;
  pendingText?: string;
  explanations: ExplanationItem[];
  loading?: boolean;
}>();

defineEmits<{
  close: [];
  open: [];
  "request-explain": [text: string];
  "clear-pending": [];
}>();

function truncate(text: string, max: number) {
  return text.length <= max ? text : text.slice(0, max) + "…";
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", {
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}
</script>

// slp/frontend-angular/src/features/source/components/explanation-panel.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NzSpinModule } from 'ng-zorro-antd/spin';
import { animate, style, transition, trigger } from '@angular/animations';
import { ExplanationItem } from '../models/source.model';

@Component({
  selector: 'app-explanation-panel',
  standalone: true,
  imports: [CommonModule, NzSpinModule],
  template: `
    <div class="fixed top-0 right-0 h-screen w-[320px] bg-[#faf9f6] border-l border-[#e8e4dc] shadow-[-4px_0_24px_rgba(0,0,0,0.06)] z-[200] flex flex-col"
         [class.translate-x-0]="isOpen"
         [class.translate-x-full]="!isOpen"
         @panelAnim
         data-testid="explanation-panel">
      <button class="absolute left-[-32px] top-1/2 -translate-y-1/2 w-8 h-12 bg-[#faf9f6] border border-[#e8e4dc] border-r-0 rounded-l-[8px] cursor-pointer flex items-center justify-center text-gray-400 transition-colors hover:text-gray-700"
              (click)="isOpen ? close.emit() : open.emit()"
              data-testid="explanation-panel-toggle-btn">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="9 18 15 12 9 6"></polyline></svg>
      </button>

      <div class="flex-1 overflow-y-auto flex flex-col">
        <div class="flex items-center justify-between px-5 pt-5 pb-4 border-b border-[#e8e4dc]">
          <div class="flex items-center gap-2">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#7c6af5" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v1M12 8v1M12 13v1M12 18v1M5.6 5.6l.7.7M17.6 5.6l-.7.7M5.6 18.4l.7-.7M17.6 18.4l-.7-.7"/><circle cx="12" cy="12" r="3"/></svg>
            <h3 class="text-sm font-semibold text-[#1a1a2e] m-0 tracking-[-0.01em]">Explanations</h3>
          </div>
          <button class="bg-transparent border-0 text-gray-400 cursor-pointer p-1 rounded transition-all hover:text-gray-700 hover:bg-gray-100"
                  (click)="close.emit()" data-testid="explanation-panel-close-btn">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
          </button>
        </div>

        <div *ngIf="pendingText" class="m-4 p-[14px] bg-white border border-[#e8e4dc] rounded-[10px]" data-testid="explanation-panel-preview">
          <p class="text-[10px] font-semibold uppercase tracking-[0.08em] text-gray-400 mt-0 mb-2">Selected text</p>
          <blockquote class="text-[13px] text-gray-700 italic border-l-[3px] border-[#7c6af5] pl-[10px] mt-0 mb-3 leading-[1.5]" data-testid="explanation-panel-preview-text">
            {{ truncate(pendingText, 120) }}
          </blockquote>
          <div class="flex gap-2">
            <button class="flex items-center gap-[5px] px-3 py-1.5 rounded-[7px] text-xs font-medium cursor-pointer border-0 bg-[#7c6af5] text-white font-[inherit] transition-all hover:bg-[#6c5ce7]"
                    (click)="requestExplain.emit(pendingText)" data-testid="explanation-panel-explain-btn">
              <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v1M12 8v1M12 13v1M12 18v1M5.6 5.6l.7.7M17.6 5.6l-.7.7M5.6 18.4l.7-.7M17.6 18.4l-.7-.7"/><circle cx="12" cy="12" r="3"/></svg>
              Explain with AI
            </button>
            <button class="flex items-center gap-[5px] px-3 py-1.5 rounded-[7px] text-xs font-medium cursor-pointer border border-[#e8e4dc] bg-white text-gray-700 font-[inherit] transition-all hover:bg-gray-50 hover:border-gray-300"
                    (click)="clearPending.emit()" data-testid="explanation-panel-clear-btn">
              <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>
              Clear
            </button>
          </div>
        </div>

        <div *ngIf="loading" class="flex flex-col items-center justify-center gap-3 px-5 py-10 text-gray-400 text-[13px] text-center flex-1" data-testid="explanation-panel-loading">
          <nz-spin nzSimple size="small"></nz-spin>
          <span>Loading...</span>
        </div>

        <div *ngIf="!loading && explanations.length === 0 && !pendingText" class="flex flex-col items-center justify-center gap-3 px-5 py-10 text-gray-400 text-[13px] text-center flex-1" data-testid="explanation-panel-empty">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="text-gray-300"><path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"></path><path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"></path></svg>
          <p>Select text in the article to get AI explanations.</p>
        </div>

        <div *ngIf="!loading && (explanations.length > 0 || pendingText)" class="py-3 px-4 flex flex-col gap-3" data-testid="explanation-panel-list">
          <div *ngFor="let exp of explanations; trackBy: trackById" class="bg-white border border-[#e8e4dc] rounded-[10px] p-[14px] transition-shadow hover:shadow-[0_2px_12px_rgba(0,0,0,0.06)]"
               [attr.data-testid]="'explanation-panel-card-' + exp.id">
            <div class="text-xs text-gray-500 italic mb-2 leading-[1.4]" [attr.data-testid]="'explanation-panel-card-quote-' + exp.id">
              <span class="text-lg text-[#7c6af5] leading-none align-[-4px] mr-0.5">"</span>
              {{ truncate(exp.textRange?.text ?? '', 80) }}
            </div>
            <div *ngIf="exp.content" class="text-[13px] text-gray-700 leading-[1.6]" [attr.data-testid]="'explanation-panel-card-content-' + exp.id">
              {{ exp.content }}
            </div>
            <div *ngIf="!exp.content" class="flex items-center gap-2 text-xs text-gray-400" [attr.data-testid]="'explanation-panel-card-pending-' + exp.id">
              <nz-spin nzSimple size="small"></nz-spin>
              <span>Generating explanation…</span>
            </div>
            <div class="text-[11px] text-[#c4bfb5] mt-2" [attr.data-testid]="'explanation-panel-card-meta-' + exp.id">
              {{ formatDate(exp.createdAt) }}
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  animations: [
    trigger('panelAnim', [
      transition(':enter', [
        style({ transform: 'translateX(100%)' }),
        animate('280ms cubic-bezier(0.4, 0, 0.2, 1)', style({ transform: 'translateX(0)' }))
      ]),
      transition(':leave', [
        animate('280ms cubic-bezier(0.4, 0, 0.2, 1)', style({ transform: 'translateX(100%)' }))
      ])
    ])
  ]
})
export class ExplanationPanelComponent {
  @Input() isOpen = false;
  @Input() pendingText: string | null = null;
  @Input() explanations: ExplanationItem[] = [];
  @Input() loading = false;

  @Output() close = new EventEmitter<void>();
  @Output() open = new EventEmitter<void>();
  @Output() requestExplain = new EventEmitter<string>();
  @Output() clearPending = new EventEmitter<void>();

  truncate(text: string, max: number): string {
    return text.length <= max ? text : text.slice(0, max) + '…';
  }

  formatDate(iso: string): string {
    return new Date(iso).toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
    });
  }

  trackById(_: number, item: ExplanationItem) { return item.id; }
}
