// slp/frontend-vue/src/features/source/components/SelectionBubble.vue
<template>
  <Teleport to="body">
    <Transition name="bubble">
      <div
        v-if="visible"
        ref="bubbleRef"
        class="absolute z-[9999] w-[296px] pointer-events-auto
               [filter:drop-shadow(0_4px_16px_rgba(0,0,0,0.12))]"
        :style="bubbleStyle"
        @mousedown.prevent
        data-testid="selection-bubble"
      >
        <!-- Actions bar -->
        <div
          class="flex items-center bg-white border border-[#e5e7eb] rounded-[10px] p-1 gap-0.5"
          data-testid="selection-bubble-bar"
        >
          <button
            class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5
                   border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer
                   text-xs font-medium whitespace-nowrap font-[inherit]
                   transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
            @click="emit('explain', selectedText)"
            data-testid="selection-bubble-explain-btn"
          >
            <Sparkles :size="13" />
            Explain
          </button>

          <button
            class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5
                   border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer
                   text-xs font-medium whitespace-nowrap font-[inherit]
                   transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
            @click="emit('grammar', selectedText)"
            data-testid="selection-bubble-grammar-btn"
          >
            <SpellCheck :size="13" />
            Grammar
          </button>

          <button
            class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5
                   border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer
                   text-xs font-medium whitespace-nowrap font-[inherit]
                   transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
            @click="emit('tts', selectedText)"
            data-testid="selection-bubble-listen-btn"
          >
            <Volume2 :size="13" />
            Listen
          </button>

          <button
            class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5
                   border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer
                   text-xs font-medium whitespace-nowrap font-[inherit]
                   transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
            @click="emit('favorite', selectedText)"
            data-testid="selection-bubble-save-btn"
          >
            <Bookmark :size="13" />
            Save
          </button>
        </div>

        <!-- Arrow (::after pseudo-element requires CSS) -->
        <div class="bubble-arrow" />
      </div>
    </Transition>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from "vue";
import { Sparkles, SpellCheck, Volume2, Bookmark } from "lucide-vue-next";

const emit = defineEmits<{
  explain:  [text: string];
  grammar:  [text: string];
  tts:      [text: string];
  favorite: [text: string];
}>();

const props = defineProps<{
  containerRef?: HTMLElement | null;
}>();

const bubbleRef    = ref<HTMLElement | null>(null);
const visible      = ref(false);
const selectedText = ref("");
const position     = ref({ x: 0, y: 0 });

const BUBBLE_WIDTH  = 296;
const BUBBLE_HEIGHT = 40;

const bubbleStyle = computed(() => ({
  left: `${position.value.x}px`,
  top:  `${position.value.y}px`,
}));

function handleSelectionChange() {
  const selection = window.getSelection();
  if (!selection || selection.isCollapsed || !selection.toString().trim()) {
    visible.value = false;
    return;
  }
  const text = selection.toString().trim();
  if (text.length < 2) { visible.value = false; return; }

  if (props.containerRef) {
    const anchor = selection.anchorNode;
    if (anchor && !props.containerRef.contains(anchor)) {
      visible.value = false;
      return;
    }
  }

  const range   = selection.getRangeAt(0);
  const rect    = range.getBoundingClientRect();
  const scrollX = window.scrollX || window.pageXOffset;
  const scrollY = window.scrollY || window.pageYOffset;

  let x = rect.left + scrollX + rect.width / 2 - BUBBLE_WIDTH / 2;
  let y = rect.top  + scrollY - BUBBLE_HEIGHT - 14;

  x = Math.max(8, Math.min(x, window.innerWidth + scrollX - BUBBLE_WIDTH - 8));
  if (rect.top < BUBBLE_HEIGHT + 20) y = rect.bottom + scrollY + 14;

  selectedText.value = text;
  position.value = { x, y };
  visible.value  = true;
}

const handleMouseUp   = () => setTimeout(handleSelectionChange, 10);
const handleMouseDown = (e: MouseEvent) => { if (bubbleRef.value?.contains(e.target as Node)) return; };
const handleKeyUp     = (e: KeyboardEvent) => {
  if (e.key === "Escape") { visible.value = false; window.getSelection()?.removeAllRanges(); }
  else setTimeout(handleSelectionChange, 10);
};

onMounted(() => {
  document.addEventListener("mouseup",          handleMouseUp);
  document.addEventListener("mousedown",        handleMouseDown);
  document.addEventListener("keyup",            handleKeyUp);
  document.addEventListener("selectionchange",  () => {
    const s = window.getSelection();
    if (!s || s.isCollapsed) visible.value = false;
  });
});

onUnmounted(() => {
  document.removeEventListener("mouseup",   handleMouseUp);
  document.removeEventListener("mousedown", handleMouseDown);
  document.removeEventListener("keyup",     handleKeyUp);
});
</script>

<style>
/*
 * Only things that cannot be expressed in Tailwind:
 *   1. ::after pseudo-element for the two-layer CSS arrow
 *   2. @keyframes for the enter/leave animations
 */

.bubble-arrow {
  position: absolute;
  bottom: -6px;
  left: 50%;
  transform: translateX(-50%);
  width: 0;
  height: 0;
  border-left: 6px solid transparent;
  border-right: 6px solid transparent;
  border-top: 6px solid #e5e7eb;
}

.bubble-arrow::after {
  content: "";
  position: absolute;
  top: -7px;
  left: -5px;
  width: 0;
  height: 0;
  border-left: 5px solid transparent;
  border-right: 5px solid transparent;
  border-top: 5px solid #ffffff;
}

.bubble-enter-active { animation: bubblePop  0.15s cubic-bezier(0.34, 1.56, 0.64, 1) forwards; }
.bubble-leave-active { animation: bubbleFade 0.1s  ease forwards; }

@keyframes bubblePop {
  from { opacity: 0; transform: translateY(6px)  scale(0.94); }
  to   { opacity: 1; transform: translateY(0)     scale(1);    }
}
@keyframes bubbleFade {
  to   { opacity: 0; transform: translateY(-3px) scale(0.97); }
}
</style>

// slp/frontend-angular/src/features/source/components/selection-bubble.component.ts
import { Component, Input, Output, EventEmitter, ElementRef, AfterViewInit, OnDestroy, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { animate, style, transition, trigger } from '@angular/animations';

@Component({
  selector: 'app-selection-bubble',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div *ngIf="visible"
         #bubbleRef
         @bubbleAnim
         class="absolute z-[9999] w-[296px] pointer-events-auto [filter:drop-shadow(0_4px_16px_rgba(0,0,0,0.12))]"
         [style.left.px]="position.x"
         [style.top.px]="position.y"
         (mousedown)="$event.preventDefault()"
         data-testid="selection-bubble">
      <div class="flex items-center bg-white border border-[#e5e7eb] rounded-[10px] p-1 gap-0.5" data-testid="selection-bubble-bar">
        <button class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5 border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer text-xs font-medium whitespace-nowrap font-[inherit] transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
                (click)="emitExplain()" data-testid="selection-bubble-explain-btn">
          <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3v1M12 8v1M12 13v1M12 18v1M5.6 5.6l.7.7M17.6 5.6l-.7.7M5.6 18.4l.7-.7M17.6 18.4l-.7-.7"/><circle cx="12" cy="12" r="3"/></svg>
          Explain
        </button>
        <button class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5 border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer text-xs font-medium whitespace-nowrap font-[inherit] transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
                (click)="emitGrammar()" data-testid="selection-bubble-grammar-btn">
          <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83"/><circle cx="12" cy="12" r="3"/></svg>
          Grammar
        </button>
        <button class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5 border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer text-xs font-medium whitespace-nowrap font-[inherit] transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
                (click)="emitTts()" data-testid="selection-bubble-listen-btn">
          <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path><path d="M19.07 4.93a10 10 0 0 1 0 14.14"></path></svg>
          Listen
        </button>
        <button class="flex items-center gap-[5px] flex-1 justify-center px-2 py-1.5 border-0 bg-transparent text-gray-700 rounded-[7px] cursor-pointer text-xs font-medium whitespace-nowrap font-[inherit] transition-all duration-[120ms] hover:bg-[#f3f4f6] hover:text-gray-900"
                (click)="emitFavorite()" data-testid="selection-bubble-save-btn">
          <svg xmlns="http://www.w3.org/2000/svg" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"/></svg>
          Save
        </button>
      </div>
      <div class="bubble-arrow"></div>
    </div>
  `,
  styles: [`
    .bubble-arrow {
      position: absolute;
      bottom: -6px;
      left: 50%;
      transform: translateX(-50%);
      width: 0;
      height: 0;
      border-left: 6px solid transparent;
      border-right: 6px solid transparent;
      border-top: 6px solid #e5e7eb;
    }
    .bubble-arrow::after {
      content: "";
      position: absolute;
      top: -7px;
      left: -5px;
      width: 0;
      height: 0;
      border-left: 5px solid transparent;
      border-right: 5px solid transparent;
      border-top: 5px solid #ffffff;
    }
  `],
  animations: [
    trigger('bubbleAnim', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(6px) scale(0.94)' }),
        animate('0.15s cubic-bezier(0.34, 1.56, 0.64, 1)',
          style({ opacity: 1, transform: 'translateY(0) scale(1)' }))
      ]),
      transition(':leave', [
        animate('0.1s ease', style({ opacity: 0, transform: 'translateY(-3px) scale(0.97)' }))
      ])
    ])
  ]
})
export class SelectionBubbleComponent implements AfterViewInit, OnDestroy {
  @Input() containerRef?: HTMLElement;
  @Output() explain = new EventEmitter<string>();
  @Output() grammar = new EventEmitter<string>();
  @Output() tts = new EventEmitter<string>();
  @Output() favorite = new EventEmitter<string>();

  visible = false;
  selectedText = '';
  position = { x: 0, y: 0 };
  private bubbleWidth = 296;
  private bubbleHeight = 40;

  ngAfterViewInit() {
    document.addEventListener('mouseup', this.onMouseUp);
    document.addEventListener('mousedown', this.onMouseDown);
    document.addEventListener('keyup', this.onKeyUp);
    document.addEventListener('selectionchange', this.onSelectionChange);
  }

  ngOnDestroy() {
    document.removeEventListener('mouseup', this.onMouseUp);
    document.removeEventListener('mousedown', this.onMouseDown);
    document.removeEventListener('keyup', this.onKeyUp);
    document.removeEventListener('selectionchange', this.onSelectionChange);
  }

  private onMouseUp = () => setTimeout(() => this.handleSelection(), 10);
  private onMouseDown = (e: MouseEvent) => {
    if (this.visible && (e.target as HTMLElement).closest('[data-testid="selection-bubble"]')) return;
    this.visible = false;
  };
  private onKeyUp = (e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      this.visible = false;
      window.getSelection()?.removeAllRanges();
    } else setTimeout(() => this.handleSelection(), 10);
  };
  private onSelectionChange = () => {
    const sel = window.getSelection();
    if (!sel || sel.isCollapsed) this.visible = false;
  };

  private handleSelection() {
    const selection = window.getSelection();
    if (!selection || selection.isCollapsed || !selection.toString().trim()) {
      this.visible = false;
      return;
    }
    const text = selection.toString().trim();
    if (text.length < 2) {
      this.visible = false;
      return;
    }
    if (this.containerRef) {
      const anchor = selection.anchorNode;
      if (anchor && !this.containerRef.contains(anchor)) {
        this.visible = false;
        return;
      }
    }
    const range = selection.getRangeAt(0);
    const rect = range.getBoundingClientRect();
    const scrollX = window.scrollX;
    const scrollY = window.scrollY;

    let x = rect.left + scrollX + rect.width / 2 - this.bubbleWidth / 2;
    let y = rect.top + scrollY - this.bubbleHeight - 14;

    x = Math.max(8, Math.min(x, window.innerWidth + scrollX - this.bubbleWidth - 8));
    if (rect.top < this.bubbleHeight + 20) y = rect.bottom + scrollY + 14;

    this.selectedText = text;
    this.position = { x, y };
    this.visible = true;
  }

  emitExplain() { this.explain.emit(this.selectedText); this.visible = false; }
  emitGrammar() { this.grammar.emit(this.selectedText); this.visible = false; }
  emitTts() { this.tts.emit(this.selectedText); this.visible = false; }
  emitFavorite() { this.favorite.emit(this.selectedText); this.visible = false; }
}
