// slp/frontend-vue/src/views/quiz/QuizForm.vue
<template>
  <MobileLayout :title="isEdit ? 'Edit Quiz' : 'Create Quiz'">
    <a-card class="shadow-sm">
      <a-form
        :model="form"
        @submit.prevent="handleSubmit"
        layout="vertical"
      >
        <a-form-item label="Title" required>
          <a-input v-model:value="form.title" placeholder="Enter quiz title" />
        </a-form-item>

        <a-form-item label="Description">
          <a-textarea v-model:value="form.description" placeholder="Describe your quiz" :rows="3" />
        </a-form-item>

        <a-form-item label="Visibility">
          <a-radio-group v-model:value="form.visibility">
            <a-radio value="private">Private (only you)</a-radio>
            <a-radio value="unlisted">Unlisted (anyone with link)</a-radio>
            <a-radio value="public">Public (visible to everyone)</a-radio>
          </a-radio-group>
        </a-form-item>

        <a-form-item label="Tags">
          <a-select
            v-model:value="form.tagNames"
            mode="tags"
            placeholder="Enter tags and press enter"
            :token-separators="[',']"
          />
        </a-form-item>

        <a-form-item>
          <a-button type="primary" html-type="submit" :loading="quizStore.loading" block>
            {{ isEdit ? 'Update Quiz' : 'Create Quiz' }}
          </a-button>
        </a-form-item>
      </a-form>
    </a-card>
  </MobileLayout>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { message } from 'ant-design-vue';
import MobileLayout from '../../components/MobileLayout.vue';
import { useQuizStore } from '../../stores/quiz';
import type { CreateQuizPayload, UpdateQuizPayload } from '../../stores/quiz';

const route = useRoute();
const router = useRouter();
const quizStore = useQuizStore();

const quizId = computed(() => route.params.id ? Number(route.params.id) : null);
const isEdit = computed(() => !!quizId.value);

const form = ref<CreateQuizPayload & { tagNames: string[] }>({
  title: '',
  description: '',
  visibility: 'private',
  tagNames: [],
});

const handleSubmit = async () => {
  if (!form.value.title.trim()) {
    message.warning('Title is required');
    return;
  }

  const payload = { ...form.value };
  if (isEdit.value) {
    const updated = await quizStore.updateQuiz(quizId.value!, payload as UpdateQuizPayload);
    if (updated) {
      message.success('Quiz updated');
      router.push(`/quiz/${updated.id}`);
    }
  } else {
    const created = await quizStore.createQuiz(payload);
    if (created) {
      message.success('Quiz created');
      router.push(`/quiz/${created.id}`);
    }
  }
};

onMounted(async () => {
  if (isEdit.value) {
    await quizStore.fetchQuizById(quizId.value!);
    if (quizStore.currentQuiz) {
      form.value = {
        title: quizStore.currentQuiz.title,
        description: quizStore.currentQuiz.description,
        visibility: quizStore.currentQuiz.visibility as any,
        tagNames: quizStore.currentQuiz.tags,
      };
    }
  }
});
</script>

// slp/frontend-angular/src/features/quiz/pages/quiz-form.component.ts
import { Component, OnInit, inject } from "@angular/core";
import { CommonModule } from "@angular/common";
import {
  FormBuilder,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from "@angular/forms";
import { ActivatedRoute, Router } from "@angular/router";
import { NzCardModule } from "ng-zorro-antd/card";
import { NzFormModule } from "ng-zorro-antd/form";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzRadioModule } from "ng-zorro-antd/radio";
import { NzButtonModule } from "ng-zorro-antd/button";
import { NzMessageService } from "ng-zorro-antd/message";
import { TranslateModule, TranslateService } from "@ngx-translate/core";
import { TagSelectorComponent } from "../../../components/tag-selector/tag-selector.component";
import { QuizService } from "../quiz.service";
import { take, filter } from "rxjs/operators";

@Component({
  selector: "app-quiz-form",
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    NzCardModule,
    NzFormModule,
    NzInputModule,
    NzRadioModule,
    NzButtonModule,
    TranslateModule,
    TagSelectorComponent,
  ],
  template: `
    <nz-card class="shadow-sm" data-testid="quiz-form-card">
      <form nz-form [formGroup]="form" (ngSubmit)="onSubmit()">
        <nz-form-item>
          <nz-form-label nzRequired>{{
            "quiz.title" | translate
          }}</nz-form-label>
          <nz-form-control>
            <input
              nz-input
              formControlName="title"
              [placeholder]="'quiz.titlePlaceholder' | translate"
              data-testid="quiz-title-input"
            />
          </nz-form-control>
        </nz-form-item>

        <nz-form-item>
          <nz-form-label>{{ "quiz.description" | translate }}</nz-form-label>
          <nz-form-control>
            <textarea
              nz-input
              formControlName="description"
              rows="3"
              [placeholder]="'quiz.descriptionPlaceholder' | translate"
              data-testid="quiz-description-input"
            ></textarea>
          </nz-form-control>
        </nz-form-item>

        <nz-form-item>
          <nz-form-label>{{ "quiz.visibility" | translate }}</nz-form-label>
          <nz-form-control>
            <nz-radio-group
              formControlName="visibility"
              data-testid="quiz-visibility-radio-group"
            >
              <label
                nz-radio
                nzValue="private"
                data-testid="quiz-visibility-private"
                >{{ "quiz.visibilityPrivate" | translate }}</label
              >
              <label
                nz-radio
                nzValue="public"
                data-testid="quiz-visibility-public"
                >{{ "quiz.visibilityPublic" | translate }}</label
              >
            </nz-radio-group>
          </nz-form-control>
        </nz-form-item>

        <nz-form-item>
          <nz-form-label>{{ "quiz.tags" | translate }}</nz-form-label>
          <nz-form-control>
            <app-tag-selector
              [formControl]="tagsControl"
              data-testid="quiz-tags-select"
            ></app-tag-selector>
          </nz-form-control>
        </nz-form-item>

        <nz-form-item>
          <button
            nz-button
            nzType="primary"
            htmlType="submit"
            [disabled]="form.invalid"
            [nzLoading]="(quizService.loading$ | async) ?? false"
            block
            data-testid="quiz-submit-button"
          >
            {{ (isEdit ? "common.save" : "common.create") | translate }}
          </button>
        </nz-form-item>
      </form>
    </nz-card>
  `,
})
export class QuizFormComponent implements OnInit {
  private fb = inject(FormBuilder);
  private route = inject(ActivatedRoute);
  private router = inject(Router);
  public quizService = inject(QuizService);
  private message = inject(NzMessageService);
  private translate = inject(TranslateService);

  form!: FormGroup;
  tagsControl = this.fb.control<string[]>([]);
  isEdit = false;
  quizId: number | null = null;

  ngOnInit(): void {
    this.form = this.fb.group({
      title: ["", Validators.required],
      description: [""],
      visibility: ["public", Validators.required],
    });

    const idParam = this.route.snapshot.paramMap.get("id");
    if (idParam && idParam !== "new") {
      this.isEdit = true;
      this.quizId = +idParam;
      this.loadQuiz();
    } else {
      this.isEdit = false;
    }
  }

  loadQuiz(): void {
    if (!this.quizId) return;
    this.quizService.fetchQuizById(this.quizId);
    this.quizService.currentQuiz$
      .pipe(
        filter((quiz) => quiz !== null),
        take(1),
      )
      .subscribe((quiz) => {
        if (quiz) {
          this.form.patchValue({
            title: quiz.title,
            description: quiz.description || "",
            visibility: quiz.visibility,
          });
          this.tagsControl.setValue(quiz.tags || []);
        } else {
          this.message.error(this.translate.instant("quiz.notFound"));
          this.router.navigate(["/quiz"]);
        }
      });
  }

  onSubmit(): void {
    if (this.form.invalid) {
      this.message.warning(this.translate.instant("quiz.fillRequired"));
      return;
    }

    const payload = {
      title: this.form.value.title,
      description: this.form.value.description || undefined,
      visibility: this.form.value.visibility,
      tagNames: this.tagsControl.value?.length
        ? this.tagsControl.value
        : undefined,
    };

    if (this.isEdit && this.quizId) {
      this.quizService.updateQuiz(this.quizId, payload).subscribe({
        next: (updated) => {
          this.message.success(this.translate.instant("quiz.updateSuccess"));
          this.router.navigate(["/quiz", updated.id]);
        },
        error: () =>
          this.message.error(this.translate.instant("quiz.updateError")),
      });
    } else {
      this.quizService.createQuiz(payload).subscribe({
        next: (created) => {
          this.message.success(this.translate.instant("quiz.createSuccess"));
          this.router.navigate(["/quiz", created.id]);
        },
        error: () =>
          this.message.error(this.translate.instant("quiz.createError")),
      });
    }
  }
}
