// slp/frontend-vue/src/components/TagSelector.vue
<template>
  <a-select
    v-model:value="selected"
    mode="tags"
    :placeholder="placeholder"
    :loading="tagStore.loading"
    :options="options"
    :token-separators="[',']"
    :max-tag-count="MAX_TAGS"
    :status="atLimit ? 'warning' : undefined"
    allow-clear
    style="width: 100%"
    data-testid="tag-selector"
    @change="handleChange"
  >
    <template v-if="tagStore.error" #notFoundContent>
      <span
        class="text-red-400 text-xs px-2"
        data-testid="tag-selector-not-found"
        >{{ tagStore.error }}</span
      >
    </template>
  </a-select>

  <div
    v-if="atLimit"
    class="text-yellow-500 text-xs mt-1"
    data-testid="tag-selector-warning"
  >
    Maximum {{ MAX_TAGS }} tags allowed.
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted } from "vue";
import { useTagStore } from "@/features/tag/stores/tagStore";

const MAX_TAGS = 10;

const props = withDefaults(
  defineProps<{
    modelValue: string[];
    placeholder?: string;
  }>(),
  { placeholder: "Select or create tags…" },
);

const emit = defineEmits<{
  (e: "update:modelValue", value: string[]): void;
}>();

const tagStore = useTagStore();

// Merge existing tags from store with any free-typed values already in modelValue,
// de-duplicated and sorted so the dropdown always shows the union.
const options = computed(() =>
  Array.from(
    new Map(
      [
        ...tagStore.tags.map((t) => ({ value: t.name, label: t.name })),
        ...props.modelValue.map((v) => ({ value: v, label: v })),
      ].map((o) => [o.value.toLowerCase(), o]),
    ).values(),
  ).sort((a, b) => a.label.localeCompare(b.label)),
);

const selected = computed<string[]>({
  get: () => props.modelValue,
  set: (val) => emit("update:modelValue", val),
});

const atLimit = computed(() => props.modelValue.length >= MAX_TAGS);

// Enforce max-10 and de-duplicate on every change
function handleChange(newVal: string[]) {
  // Normalise: trim + lowercase for de-dup comparison, but keep original casing
  const seen = new Set<string>();
  const clean = newVal
    .map((v) => v.trim())
    .filter((v) => {
      if (!v) return false;
      const key = v.toLowerCase();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .slice(0, MAX_TAGS); // hard cap

  emit("update:modelValue", clean);
}

onMounted(() => tagStore.fetchTags());
</script>

// slp/frontend-angular/src/components/tag-selector/tag-selector.component.ts
import { Component, forwardRef, OnInit, Input } from "@angular/core";
import {
  ControlValueAccessor,
  NG_VALUE_ACCESSOR,
  FormControl,
  ReactiveFormsModule,
  FormsModule,
} from "@angular/forms";
import { CommonModule } from "@angular/common";
import { NzSelectModule } from "ng-zorro-antd/select";
import { TagService, TagDto } from "./tag.service";
import { finalize } from "rxjs/operators";

@Component({
  selector: "app-tag-selector",
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule, NzSelectModule],
  templateUrl: "./tag-selector.component.html",
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => TagSelectorComponent),
      multi: true,
    },
  ],
})
export class TagSelectorComponent implements ControlValueAccessor, OnInit {
  @Input() placeholder = "Select or create tags...";

  tags: TagDto[] = [];
  loading = false;
  error: string | null = null;
  maxTags = 10;
  control = new FormControl<string[]>([]);

  private onChange: any = () => {};
  private onTouched: any = () => {};

  constructor(private tagService: TagService) {}

  // Getter để tạo danh sách options (giống logic computed trong Vue)
  get options() {
    const apiTags = this.tags.map((t) => ({ value: t.name, label: t.name }));
    const currentValues = (this.control.value || []).map((v) => ({
      value: v,
      label: v,
    }));

    // De-duplicate dựa trên lowercase value
    const map = new Map();
    [...apiTags, ...currentValues].forEach((opt) => {
      map.set(opt.value.toLowerCase(), opt);
    });

    return Array.from(map.values()).sort((a, b) =>
      a.label.localeCompare(b.label),
    );
  }

  get atLimit(): boolean {
    return (this.control.value?.length || 0) >= this.maxTags;
  }

  ngOnInit(): void {
    this.loadTags();
    this.control.valueChanges.subscribe((value) => {
      this.onChange(value);
    });
  }

  loadTags(): void {
    this.loading = true;
    this.error = null;
    this.tagService
      .fetchTags()
      .pipe(finalize(() => (this.loading = false)))
      .subscribe({
        next: (tags) => (this.tags = tags),
        error: (err) => {
          this.error = "Failed to load tags";
          console.error(err);
        },
      });
  }

  handleChange(newVal: string[]): void {
    if (!newVal) return;

    const seen = new Set<string>();
    const clean = newVal
      .map((v) => v.trim())
      .filter((v) => {
        if (!v) return false;
        const key = v.toLowerCase();
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
      })
      .slice(0, this.maxTags);

    // Cập nhật lại control với dữ liệu đã làm sạch (tránh vòng lặp vô tận bằng emitEvent: false)
    this.control.setValue(clean, { emitEvent: false });
    this.onChange(clean);
    this.onTouched();
  }

  // ControlValueAccessor methods
  writeValue(value: string[] | null): void {
    this.control.setValue(value || [], { emitEvent: false });
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }
  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState(isDisabled: boolean): void {
    isDisabled ? this.control.disable() : this.control.enable();
  }
}

<nz-select
  nzMode="tags"
  [nzPlaceHolder]="placeholder"
  [nzLoading]="loading"
  [nzStatus]="atLimit ? 'warning' : ''"
  [formControl]="control"
  (ngModelChange)="handleChange($event)"
  style="width: 100%"
  [nzNotFoundContent]="notFoundTpl"
  data-testid="tag-selector"
>
  <nz-option
    *ngFor="let opt of options"
    [nzValue]="opt.value"
    [nzLabel]="opt.label"
  ></nz-option>
</nz-select>

<ng-template #notFoundTpl>
  <span
    *ngIf="error"
    class="text-red-400 text-xs px-2"
    data-testid="tag-selector-not-found"
  >
    {{ error }}
  </span>
</ng-template>

<div
  *ngIf="atLimit"
  class="text-yellow-500 text-xs mt-1"
  data-testid="tag-selector-warning"
>
  Maximum {{ maxTags }} tags allowed.
</div>
