// slp/frontend-angular/src/features/admin/components/admin-log-filters.component.ts
import { Component, output, signal } from "@angular/core";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";
import { NzSelectModule } from "ng-zorro-antd/select";
import { NzDatePickerModule } from "ng-zorro-antd/date-picker";
import { NzInputModule } from "ng-zorro-antd/input";
import { NzButtonModule } from "ng-zorro-antd/button";
import dayjs, { Dayjs } from "dayjs";

@Component({
  selector: "app-admin-log-filters",
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    NzSelectModule,
    NzDatePickerModule,
    NzInputModule,
    NzButtonModule,
  ],
  template: `
    <div class="log-filters">
      <nz-select
        data-testid="log-filter-action"
        [(ngModel)]="filters.action"
        nzAllowClear
        nzPlaceHolder="Action"
        style="width: 150px"
      >
        <nz-option
          data-testid="log-filter-action-option-ban_user"
          nzValue="ban_user"
          nzLabel="ban_user"
        ></nz-option>
        <nz-option
          data-testid="log-filter-action-option-unban_user"
          nzValue="unban_user"
          nzLabel="unban_user"
        ></nz-option>
        <nz-option
          data-testid="log-filter-action-option-disable_quiz"
          nzValue="disable_quiz"
          nzLabel="disable_quiz"
        ></nz-option>
        <nz-option
          data-testid="log-filter-action-option-enable_quiz"
          nzValue="enable_quiz"
          nzLabel="enable_quiz"
        ></nz-option>
        <nz-option
          data-testid="log-filter-action-option-delete_comment"
          nzValue="delete_comment"
          nzLabel="delete_comment"
        ></nz-option>
        <nz-option
          data-testid="log-filter-action-option-restore_comment"
          nzValue="restore_comment"
          nzLabel="restore_comment"
        ></nz-option>
      </nz-select>

      <nz-select
        data-testid="log-filter-target-type"
        [(ngModel)]="filters.targetType"
        nzAllowClear
        nzPlaceHolder="Target type"
        style="width: 120px"
      >
        <nz-option
          data-testid="log-filter-target-type-option-user"
          nzValue="user"
          nzLabel="user"
        ></nz-option>
        <nz-option
          data-testid="log-filter-target-type-option-quiz"
          nzValue="quiz"
          nzLabel="quiz"
        ></nz-option>
        <nz-option
          data-testid="log-filter-target-type-option-comment"
          nzValue="comment"
          nzLabel="comment"
        ></nz-option>
      </nz-select>

      <nz-range-picker
        data-testid="log-filter-date-range"
        [(ngModel)]="filters.dateRange"
        [nzShowTime]="true"
        nzFormat="yyyy-MM-dd HH:mm"
        style="width: 280px"
      ></nz-range-picker>

      <nz-input-group [nzSuffix]="suffixTemplate">
        <input
          nz-input
          data-testid="log-filter-search"
          [(ngModel)]="filters.search"
          placeholder="Search by admin, action, target ID, details..."
        />
      </nz-input-group>
      <ng-template #suffixTemplate>
        <i nz-icon nzType="search" (click)="apply()"></i>
      </ng-template>

      <button
        nz-button
        nzType="primary"
        data-testid="log-apply-filters"
        (click)="apply()"
      >
        Apply
      </button>
    </div>
  `,
  styles: [
    `
      .log-filters {
        display: flex;
        flex-wrap: wrap;
        gap: 8px;
        margin-bottom: 16px;
        align-items: center;
      }
      @media (max-width: 768px) {
        .log-filters > * {
          width: 100% !important;
        }
      }
    `,
  ],
})
export class AdminLogFiltersComponent {
  applyFilters = output<any>();

  filters = {
    action: null as string | null,
    targetType: null as string | null,
    dateRange: null as [Dayjs, Dayjs] | null,
    search: "",
  };

  apply() {
    const params: any = {
      action: this.filters.action,
      targetType: this.filters.targetType,
      search: this.filters.search || undefined,
    };
    if (this.filters.dateRange) {
      params.from = this.filters.dateRange[0].toISOString();
      params.to = this.filters.dateRange[1].toISOString();
    }
    this.applyFilters.emit(params);
  }
}

// slp/frontend-vue/src/features/admin/components/AdminLogFilters.vue
<template>
  <div class="log-filters">
    <a-select
      v-model:value="filters.action"
      placeholder="Action"
      allow-clear
      style="width: 150px"
      data-testid="log-filter-action"
    >
      <a-select-option value="ban_user">ban_user</a-select-option>
      <a-select-option value="unban_user">unban_user</a-select-option>
      <a-select-option value="disable_quiz">disable_quiz</a-select-option>
      <a-select-option value="enable_quiz">enable_quiz</a-select-option>
      <a-select-option value="delete_comment">delete_comment</a-select-option>
      <a-select-option value="restore_comment">restore_comment</a-select-option>
    </a-select>

    <a-select
      v-model:value="filters.targetType"
      placeholder="Target type"
      allow-clear
      style="width: 120px"
      data-testid="log-filter-target-type"
    >
      <a-select-option value="user">user</a-select-option>
      <a-select-option value="quiz">quiz</a-select-option>
      <a-select-option value="comment">comment</a-select-option>
    </a-select>

    <a-range-picker
      v-model:value="filters.dateRange"
      show-time
      format="YYYY-MM-DD HH:mm"
      placeholder="From – To"
      style="width: 280px"
      data-testid="log-filter-date-range"
    />

    <a-input-search
      v-model:value="filters.search"
      placeholder="Search by admin, action, target ID, details..."
      style="width: 240px"
      @search="applyFilters"
      data-testid="log-filter-search"
    />

    <a-button type="primary" @click="applyFilters" data-testid="log-apply-filters">
      Apply
    </a-button>
  </div>
</template>

<script setup lang="ts">
import { reactive } from 'vue';
import type { Dayjs } from 'dayjs';

const emit = defineEmits<{
  (e: 'apply', filters: any): void;
}>();

const filters = reactive({
  action: null as string | null,
  targetType: null as string | null,
  dateRange: null as [Dayjs, Dayjs] | null,
  search: ''
});

function applyFilters() {
  const params: any = {
    action: filters.action,
    targetType: filters.targetType,
    search: filters.search || undefined
  };
  if (filters.dateRange) {
    params.from = filters.dateRange[0].toISOString();
    params.to = filters.dateRange[1].toISOString();
  }
  emit('apply', params);
}
</script>

<style scoped>
.log-filters {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-bottom: 16px;
  align-items: center;
}
@media (max-width: 768px) {
  .log-filters > * {
    width: 100% !important;
  }
}
</style>
